"""
Static game data for the Nuzlocke scraper.

Contains everything that is hand-authored and game-specific:
  HM_MOVES          — which moves are HMs and their slot number, per version
  BADGE_OBEDIENCE   — badge-count thresholds for outsider-Pokémon obedience
  TRAINER_DEFS      — gym leaders, E4, champions, rivals (Bulbapedia page names)
  GAME_STATIC       — starters, static encounters, gift Pokémon, in-game trades
  ROUTE_ORDER       — location unlock order with prerequisites
  BULBA_ITEM_FIELDS — Bulbapedia {{itemlist}} field names for each version,
                      used to extract TM locations from item pages
"""

from __future__ import annotations

# ── HM moves per canonical version ────────────────────────────────────────────
# Values are "hmNN" strings; only the representative version is listed and then
# aliased to its pair(s) below.

HM_MOVES: dict[str, dict[str, str]] = {
    "red":       {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","flash":"hm05"},
    "gold":      {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","flash":"hm05","whirlpool":"hm06","waterfall":"hm07"},
    "ruby":      {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","flash":"hm05","rock-smash":"hm06","waterfall":"hm07","dive":"hm08"},
    "firered":   {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","flash":"hm05","rock-smash":"hm06","waterfall":"hm07"},
    "diamond":   {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","defog":"hm05","rock-smash":"hm06","waterfall":"hm07","rock-climb":"hm08"},
    "heartgold": {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","whirlpool":"hm05","rock-smash":"hm06","waterfall":"hm07","rock-climb":"hm08"},
    "black":     {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","waterfall":"hm05","dive":"hm06"},
    "x":         {"cut":"hm01","fly":"hm02","surf":"hm03","strength":"hm04","waterfall":"hm05","rock-smash":"hm06"},
    "sun":       {},  # Gen 7 uses Ride Pokémon — no HMs
}
for _a, _b in [
    ("blue","red"),("yellow","red"),
    ("silver","gold"),("crystal","gold"),
    ("sapphire","ruby"),("emerald","ruby"),
    ("leafgreen","firered"),
    ("pearl","diamond"),("platinum","diamond"),
    ("soulsilver","heartgold"),
    ("white","black"),("black-2","black"),("white-2","black"),
    ("y","x"),("omega-ruby","x"),("alpha-sapphire","x"),
    ("moon","sun"),("ultra-sun","sun"),("ultra-moon","sun"),
]:
    HM_MOVES.setdefault(_a, HM_MOVES.get(_b, {}))


# ── Bulbapedia itemlist field names for TM location scraping ───────────────────
# Each entry is a list of candidate field names tried in order; Bulbapedia's
# {{itemlist}} template is inconsistent across generations and editors.
# Only the canonical version per pair is listed; aliases share the same fields.

BULBA_ITEM_FIELDS: dict[str, list[str]] = {
    "red":          ["Red and Blue", "Red"],
    "yellow":       ["Yellow"],
    "gold":         ["Gold and Silver", "Gold"],
    "crystal":      ["Crystal"],
    "ruby":         ["Ruby and Sapphire", "Ruby"],
    "emerald":      ["Emerald"],
    "firered":      ["FireRed and LeafGreen", "FireRed"],
    "diamond":      ["Diamond and Pearl", "Diamond"],
    "platinum":     ["Platinum"],
    "heartgold":    ["HeartGold and SoulSilver", "HeartGold", "HGSS"],
    "black":        ["Black and White", "Black"],
    "black-2":      ["Black 2 and White 2", "Black 2"],
    "x":            ["X and Y", "X"],
    "omega-ruby":   ["Omega Ruby and Alpha Sapphire", "Omega Ruby", "ORAS"],
    "sun":          ["Sun and Moon", "Sun"],
    "ultra-sun":    ["Ultra Sun and Ultra Moon", "Ultra Sun", "USUM"],
}
for _a, _b in [
    ("blue","red"),
    ("silver","gold"),
    ("sapphire","ruby"),
    ("leafgreen","firered"),
    ("pearl","diamond"),
    ("soulsilver","heartgold"),
    ("white","black"),("white-2","black-2"),
    ("y","x"),("alpha-sapphire","omega-ruby"),
    ("moon","sun"),("ultra-moon","ultra-sun"),
]:
    BULBA_ITEM_FIELDS.setdefault(_a, BULBA_ITEM_FIELDS.get(_b, []))


# ── Badge obedience thresholds ─────────────────────────────────────────────────
# Applies to outsider (traded/transferred) Pokémon only.
# Each entry = {"badges": N, "max_level": M} meaning "after earning N badges,
# outsider Pokémon up to level M obey".

BADGE_OBEDIENCE: dict[str, list[dict]] = {
    # RBY: Cascade Badge (#2), Soul Badge (#5), Volcano Badge (#7), Earth Badge (#8)
    "red":       [{"badges":0,"max_level":10},{"badges":2,"max_level":30},
                  {"badges":5,"max_level":50},{"badges":7,"max_level":70},{"badges":8,"max_level":100}],
    # GSC/HGSS: increments of 10 per badge
    "gold":      [{"badges":0,"max_level":10},{"badges":1,"max_level":20},
                  {"badges":2,"max_level":30},{"badges":3,"max_level":40},
                  {"badges":4,"max_level":50},{"badges":5,"max_level":60},
                  {"badges":6,"max_level":70},{"badges":7,"max_level":80},{"badges":8,"max_level":100}],
    "heartgold": [{"badges":0,"max_level":10},{"badges":1,"max_level":20},
                  {"badges":2,"max_level":30},{"badges":3,"max_level":40},
                  {"badges":4,"max_level":50},{"badges":5,"max_level":60},
                  {"badges":6,"max_level":70},{"badges":7,"max_level":80},{"badges":8,"max_level":100}],
    # RSE: Stone (#1 → 20), Dynamo (#3 → 30), Balance (#5 → 50), Mind (#7 → 70)
    "ruby":      [{"badges":0,"max_level":20},{"badges":2,"max_level":30},
                  {"badges":4,"max_level":50},{"badges":6,"max_level":70},{"badges":8,"max_level":100}],
    # DPPt: Coal (#1 → 20), Forest (#2 → 30), Fen (#4 → 50), Mine (#6 → 70)
    "diamond":   [{"badges":0,"max_level":20},{"badges":2,"max_level":30},
                  {"badges":4,"max_level":50},{"badges":6,"max_level":70},{"badges":8,"max_level":100}],
    # BW: Trio (#1 → 20), Bolt (#4 → 35), Jet (#6 → 50), Legend (#8 → 100 implied)
    "black":     [{"badges":0,"max_level":20},{"badges":2,"max_level":35},
                  {"badges":4,"max_level":50},{"badges":6,"max_level":65},{"badges":8,"max_level":100}],
    # XY: Bug (#1 → 25), Cliff (#2 → 40), Plant (#4 → 55), Psychic (#6 → 70)
    "x":         [{"badges":0,"max_level":10},{"badges":1,"max_level":25},
                  {"badges":2,"max_level":40},{"badges":4,"max_level":55},
                  {"badges":6,"max_level":70},{"badges":8,"max_level":100}],
    "sun":       [],  # No outsider-obedience mechanic in Gen 7
}
for _a, _b in [
    ("blue","red"),("yellow","red"),("firered","red"),("leafgreen","red"),
    ("silver","gold"),("crystal","gold"),("soulsilver","heartgold"),
    ("sapphire","ruby"),("emerald","ruby"),("omega-ruby","ruby"),("alpha-sapphire","ruby"),
    ("pearl","diamond"),("platinum","diamond"),
    ("white","black"),("black-2","black"),("white-2","black"),
    ("y","x"),
    ("moon","sun"),("ultra-sun","sun"),("ultra-moon","sun"),
]:
    BADGE_OBEDIENCE.setdefault(_a, BADGE_OBEDIENCE.get(_b, []))


# ── Trainer definitions ────────────────────────────────────────────────────────
# "class": gym_leader | elite_four | champion | rival | boss
# "page":  Bulbapedia article title (spaces handled by the API)

_KANTO_GYMS_RBY = [
    {"name":"Brock",     "class":"gym_leader","specialty":"rock",    "badge":"Boulder Badge","order":1,"page":"Brock"},
    {"name":"Misty",     "class":"gym_leader","specialty":"water",   "badge":"Cascade Badge","order":2,"page":"Misty"},
    {"name":"Lt. Surge", "class":"gym_leader","specialty":"electric","badge":"Thunder Badge","order":3,"page":"Lt. Surge"},
    {"name":"Erika",     "class":"gym_leader","specialty":"grass",   "badge":"Rainbow Badge","order":4,"page":"Erika"},
    {"name":"Koga",      "class":"gym_leader","specialty":"poison",  "badge":"Soul Badge",   "order":5,"page":"Koga"},
    {"name":"Sabrina",   "class":"gym_leader","specialty":"psychic", "badge":"Marsh Badge",  "order":6,"page":"Sabrina"},
    {"name":"Blaine",    "class":"gym_leader","specialty":"fire",    "badge":"Volcano Badge","order":7,"page":"Blaine"},
    {"name":"Giovanni",  "class":"gym_leader","specialty":"ground",  "badge":"Earth Badge",  "order":8,"page":"Giovanni"},
]
_KANTO_E4_RBY = [
    {"name":"Lorelei","class":"elite_four","specialty":"ice",     "order":1,"page":"Lorelei"},
    {"name":"Bruno",  "class":"elite_four","specialty":"fighting","order":2,"page":"Bruno (Elite Four)"},
    {"name":"Agatha", "class":"elite_four","specialty":"ghost",   "order":3,"page":"Agatha"},
    {"name":"Lance",  "class":"elite_four","specialty":"dragon",  "order":4,"page":"Lance (game)"},
    {"name":"Blue",   "class":"champion",  "specialty":"mixed",           "page":"Blue (game)"},
    {"name":"Gary",   "class":"rival",  "page":"Blue (game)",
     "rival_starter_map": {
         "charmander":"bulbasaur","charmeleon":"bulbasaur","charizard":"bulbasaur",
         "squirtle":"charmander","wartortle":"charmander","blastoise":"charmander",
         "bulbasaur":"squirtle","ivysaur":"squirtle","venusaur":"squirtle",
     }},
]

_JOHTO_GYMS = [
    {"name":"Falkner","class":"gym_leader","specialty":"flying",  "badge":"Zephyr Badge",  "order":1,"page":"Falkner"},
    {"name":"Bugsy",  "class":"gym_leader","specialty":"bug",     "badge":"Hive Badge",    "order":2,"page":"Bugsy"},
    {"name":"Whitney","class":"gym_leader","specialty":"normal",  "badge":"Plain Badge",   "order":3,"page":"Whitney"},
    {"name":"Morty",  "class":"gym_leader","specialty":"ghost",   "badge":"Fog Badge",     "order":4,"page":"Morty"},
    {"name":"Chuck",  "class":"gym_leader","specialty":"fighting","badge":"Storm Badge",   "order":5,"page":"Chuck"},
    {"name":"Jasmine","class":"gym_leader","specialty":"steel",   "badge":"Mineral Badge", "order":6,"page":"Jasmine"},
    {"name":"Pryce",  "class":"gym_leader","specialty":"ice",     "badge":"Glacier Badge", "order":7,"page":"Pryce"},
    {"name":"Clair",  "class":"gym_leader","specialty":"dragon",  "badge":"Rising Badge",  "order":8,"page":"Clair"},
]
_JOHTO_E4 = [
    {"name":"Will",  "class":"elite_four","specialty":"psychic", "order":1,"page":"Will (Elite Four)"},
    {"name":"Koga",  "class":"elite_four","specialty":"poison",  "order":2,"page":"Koga"},
    {"name":"Bruno", "class":"elite_four","specialty":"fighting","order":3,"page":"Bruno (Elite Four)"},
    {"name":"Karen", "class":"elite_four","specialty":"dark",    "order":4,"page":"Karen (Elite Four)"},
    {"name":"Lance", "class":"champion",  "specialty":"dragon",           "page":"Lance (game)"},
    {"name":"Silver","class":"rival",  "page":"Silver (game)",
     "rival_starter_map": {
         "cyndaquil":"chikorita","quilava":"chikorita","typhlosion":"chikorita",
         "totodile":"cyndaquil","croconaw":"cyndaquil","feraligatr":"cyndaquil",
         "chikorita":"totodile","bayleef":"totodile","meganium":"totodile",
     }},
]
_KANTO_GYMS_HGSS = [
    {"name":"Brock",     "class":"gym_leader","specialty":"rock",    "badge":"Boulder Badge","order":9, "page":"Brock",        "post_game":True,"region":"kanto"},
    {"name":"Misty",     "class":"gym_leader","specialty":"water",   "badge":"Cascade Badge","order":10,"page":"Misty",        "post_game":True,"region":"kanto"},
    {"name":"Lt. Surge", "class":"gym_leader","specialty":"electric","badge":"Thunder Badge","order":11,"page":"Lt. Surge",    "post_game":True,"region":"kanto"},
    {"name":"Erika",     "class":"gym_leader","specialty":"grass",   "badge":"Rainbow Badge","order":12,"page":"Erika",        "post_game":True,"region":"kanto"},
    {"name":"Janine",    "class":"gym_leader","specialty":"poison",  "badge":"Soul Badge",   "order":13,"page":"Janine",       "post_game":True,"region":"kanto"},
    {"name":"Sabrina",   "class":"gym_leader","specialty":"psychic", "badge":"Marsh Badge",  "order":14,"page":"Sabrina",      "post_game":True,"region":"kanto"},
    {"name":"Blaine",    "class":"gym_leader","specialty":"fire",    "badge":"Volcano Badge","order":15,"page":"Blaine",       "post_game":True,"region":"kanto"},
    {"name":"Blue",      "class":"gym_leader","specialty":"mixed",   "badge":"Earth Badge",  "order":16,"page":"Blue (game)", "post_game":True,"region":"kanto"},
]

_HOENN_GYMS = [
    {"name":"Roxanne",    "class":"gym_leader","specialty":"rock",    "badge":"Stone Badge",   "order":1,"page":"Roxanne"},
    {"name":"Brawly",     "class":"gym_leader","specialty":"fighting","badge":"Knuckle Badge", "order":2,"page":"Brawly"},
    {"name":"Wattson",    "class":"gym_leader","specialty":"electric","badge":"Dynamo Badge",  "order":3,"page":"Wattson"},
    {"name":"Flannery",   "class":"gym_leader","specialty":"fire",    "badge":"Heat Badge",    "order":4,"page":"Flannery"},
    {"name":"Norman",     "class":"gym_leader","specialty":"normal",  "badge":"Balance Badge", "order":5,"page":"Norman"},
    {"name":"Winona",     "class":"gym_leader","specialty":"flying",  "badge":"Feather Badge", "order":6,"page":"Winona"},
    {"name":"Tate & Liza","class":"gym_leader","specialty":"psychic", "badge":"Mind Badge",    "order":7,"page":"Tate and Liza"},
    {"name":"Wallace",    "class":"gym_leader","specialty":"water",   "badge":"Rain Badge",    "order":8,"page":"Wallace"},
]
_HOENN_E4_RS = [
    {"name":"Sidney", "class":"elite_four","specialty":"dark",   "order":1,"page":"Sidney"},
    {"name":"Phoebe", "class":"elite_four","specialty":"ghost",  "order":2,"page":"Phoebe"},
    {"name":"Glacia", "class":"elite_four","specialty":"ice",    "order":3,"page":"Glacia"},
    {"name":"Drake",  "class":"elite_four","specialty":"dragon", "order":4,"page":"Drake (Elite Four)"},
    {"name":"Steven", "class":"champion",  "specialty":"steel",           "page":"Steven Stone"},
    {"name":"Brendan","class":"rival",  "page":"Brendan",
     "rival_starter_map": {
         "torchic":"treecko","combusken":"treecko","blaziken":"treecko",
         "mudkip":"torchic","marshtomp":"torchic","swampert":"torchic",
         "treecko":"mudkip","grovyle":"mudkip","sceptile":"mudkip",
     }},
    {"name":"May",    "class":"rival",  "page":"May",
     "rival_starter_map": {
         "torchic":"treecko","combusken":"treecko","blaziken":"treecko",
         "mudkip":"torchic","marshtomp":"torchic","swampert":"torchic",
         "treecko":"mudkip","grovyle":"mudkip","sceptile":"mudkip",
     }},
]

_SINNOH_GYMS = [
    {"name":"Roark",        "class":"gym_leader","specialty":"rock",    "badge":"Coal Badge",    "order":1,"page":"Roark"},
    {"name":"Gardenia",     "class":"gym_leader","specialty":"grass",   "badge":"Forest Badge",  "order":2,"page":"Gardenia"},
    {"name":"Maylene",      "class":"gym_leader","specialty":"fighting","badge":"Cobble Badge",  "order":3,"page":"Maylene"},
    {"name":"Crasher Wake", "class":"gym_leader","specialty":"water",   "badge":"Fen Badge",     "order":4,"page":"Crasher Wake"},
    {"name":"Fantina",      "class":"gym_leader","specialty":"ghost",   "badge":"Relic Badge",   "order":5,"page":"Fantina"},
    {"name":"Byron",        "class":"gym_leader","specialty":"steel",   "badge":"Mine Badge",    "order":6,"page":"Byron"},
    {"name":"Candice",      "class":"gym_leader","specialty":"ice",     "badge":"Icicle Badge",  "order":7,"page":"Candice"},
    {"name":"Volkner",      "class":"gym_leader","specialty":"electric","badge":"Beacon Badge",  "order":8,"page":"Volkner"},
]
_SINNOH_E4 = [
    {"name":"Aaron",  "class":"elite_four","specialty":"bug",     "order":1,"page":"Aaron"},
    {"name":"Bertha", "class":"elite_four","specialty":"ground",  "order":2,"page":"Bertha"},
    {"name":"Flint",  "class":"elite_four","specialty":"fire",    "order":3,"page":"Flint (Elite Four)"},
    {"name":"Lucian", "class":"elite_four","specialty":"psychic", "order":4,"page":"Lucian"},
    {"name":"Cynthia","class":"champion",  "specialty":"mixed",           "page":"Cynthia"},
    {"name":"Barry",  "class":"rival",  "page":"Barry",
     "rival_starter_map": {
         "chimchar":"turtwig","monferno":"turtwig","infernape":"turtwig",
         "piplup":"chimchar","prinplup":"chimchar","empoleon":"chimchar",
         "turtwig":"piplup","grotle":"piplup","torterra":"piplup",
     }},
]

_UNOVA_GYMS_BW = [
    {"name":"Cilan / Chili / Cress","class":"gym_leader","specialty":"grass/fire/water","badge":"Trio Badge",  "order":1,"page":"Cilan"},
    {"name":"Lenora",  "class":"gym_leader","specialty":"normal",  "badge":"Basic Badge",  "order":2,"page":"Lenora"},
    {"name":"Burgh",   "class":"gym_leader","specialty":"bug",     "badge":"Insect Badge", "order":3,"page":"Burgh"},
    {"name":"Elesa",   "class":"gym_leader","specialty":"electric","badge":"Bolt Badge",   "order":4,"page":"Elesa"},
    {"name":"Clay",    "class":"gym_leader","specialty":"ground",  "badge":"Quake Badge",  "order":5,"page":"Clay"},
    {"name":"Skyla",   "class":"gym_leader","specialty":"flying",  "badge":"Jet Badge",    "order":6,"page":"Skyla"},
    {"name":"Brycen",  "class":"gym_leader","specialty":"ice",     "badge":"Freeze Badge", "order":7,"page":"Brycen"},
    {"name":"Iris / Drayden","class":"gym_leader","specialty":"dragon","badge":"Legend Badge","order":8,"page":"Iris"},
]
_UNOVA_E4_BW = [
    {"name":"Shauntal","class":"elite_four","specialty":"ghost",   "order":1,"page":"Shauntal"},
    {"name":"Marshal", "class":"elite_four","specialty":"fighting","order":2,"page":"Marshal"},
    {"name":"Grimsley","class":"elite_four","specialty":"dark",    "order":3,"page":"Grimsley"},
    {"name":"Caitlin", "class":"elite_four","specialty":"psychic", "order":4,"page":"Caitlin"},
    {"name":"Alder",   "class":"champion",  "specialty":"mixed",           "page":"Alder"},
    {"name":"Cheren",  "class":"rival",                                    "page":"Cheren"},
    {"name":"Bianca",  "class":"rival",                                    "page":"Bianca"},
    {"name":"N",       "class":"boss",      "specialty":"mixed",           "page":"N"},
]

_KALOS_GYMS = [
    {"name":"Viola",   "class":"gym_leader","specialty":"bug",     "badge":"Bug Badge",     "order":1,"page":"Viola"},
    {"name":"Grant",   "class":"gym_leader","specialty":"rock",    "badge":"Cliff Badge",   "order":2,"page":"Grant"},
    {"name":"Korrina", "class":"gym_leader","specialty":"fighting","badge":"Rumble Badge",  "order":3,"page":"Korrina"},
    {"name":"Ramos",   "class":"gym_leader","specialty":"grass",   "badge":"Plant Badge",   "order":4,"page":"Ramos"},
    {"name":"Clemont", "class":"gym_leader","specialty":"electric","badge":"Voltage Badge", "order":5,"page":"Clemont"},
    {"name":"Valerie", "class":"gym_leader","specialty":"fairy",   "badge":"Fairy Badge",   "order":6,"page":"Valerie"},
    {"name":"Olympia", "class":"gym_leader","specialty":"psychic", "badge":"Psychic Badge", "order":7,"page":"Olympia"},
    {"name":"Wulfric", "class":"gym_leader","specialty":"ice",     "badge":"Iceberg Badge", "order":8,"page":"Wulfric"},
]
_KALOS_E4 = [
    {"name":"Malva",   "class":"elite_four","specialty":"fire",   "order":1,"page":"Malva"},
    {"name":"Siebold", "class":"elite_four","specialty":"water",  "order":2,"page":"Siebold"},
    {"name":"Wikstrom","class":"elite_four","specialty":"steel",  "order":3,"page":"Wikstrom"},
    {"name":"Drasna",  "class":"elite_four","specialty":"dragon", "order":4,"page":"Drasna"},
    {"name":"Diantha", "class":"champion",  "specialty":"mixed",           "page":"Diantha"},
    {"name":"Calem",   "class":"rival",  "page":"Calem",
     "rival_starter_map": {
         "fennekin":"chespin","braixen":"chespin","delphox":"chespin",
         "froakie":"fennekin","frogadier":"fennekin","greninja":"fennekin",
         "chespin":"froakie","quilladin":"froakie","chesnaught":"froakie",
     }},
    {"name":"Serena",  "class":"rival",  "page":"Serena",
     "rival_starter_map": {
         "fennekin":"chespin","braixen":"chespin","delphox":"chespin",
         "froakie":"fennekin","frogadier":"fennekin","greninja":"fennekin",
         "chespin":"froakie","quilladin":"froakie","chesnaught":"froakie",
     }},
]

# Gen 7: trial captains + island kahunas (mapped as gym_leader for consistency)
_ALOLA_CAPTAINS = [
    {"name":"Ilima",    "class":"gym_leader","specialty":"normal",  "badge":"Normalium Z",  "order":1,"page":"Ilima"},
    {"name":"Lana",     "class":"gym_leader","specialty":"water",   "badge":"Waterium Z",   "order":2,"page":"Lana"},
    {"name":"Kiawe",    "class":"gym_leader","specialty":"fire",    "badge":"Firium Z",     "order":3,"page":"Kiawe"},
    {"name":"Mallow",   "class":"gym_leader","specialty":"grass",   "badge":"Grassium Z",   "order":4,"page":"Mallow"},
    {"name":"Sophocles","class":"gym_leader","specialty":"electric","badge":"Electrium Z",  "order":5,"page":"Sophocles"},
    {"name":"Acerola",  "class":"gym_leader","specialty":"ghost",   "badge":"Ghostium Z",   "order":6,"page":"Acerola"},
    {"name":"Mina",     "class":"gym_leader","specialty":"fairy",   "badge":"Fairium Z",    "order":7,"page":"Mina"},
    {"name":"Hapu",     "class":"gym_leader","specialty":"ground",  "badge":"Groundium Z",  "order":8,"page":"Hapu"},
]
_ALOLA_E4 = [
    {"name":"Molayne", "class":"elite_four","specialty":"steel",  "order":1,"page":"Molayne"},
    {"name":"Olivia",  "class":"elite_four","specialty":"rock",   "order":2,"page":"Olivia"},
    {"name":"Acerola", "class":"elite_four","specialty":"ghost",  "order":3,"page":"Acerola"},
    {"name":"Kahili",  "class":"elite_four","specialty":"flying", "order":4,"page":"Kahili"},
    {"name":"Kukui",   "class":"champion",  "specialty":"mixed",           "page":"Professor Kukui"},
    {"name":"Hau",     "class":"rival",  "page":"Hau",
     "rival_starter_map": {
         "popplio":"rowlet","brionne":"rowlet","primarina":"rowlet",
         "rowlet":"litten","dartrix":"litten","decidueye":"litten",
         "litten":"popplio","torracat":"popplio","incineroar":"popplio",
     }},
    {"name":"Gladion", "class":"rival",                                    "page":"Gladion"},
    {"name":"Guzma",   "class":"boss",      "specialty":"bug",             "page":"Guzma"},
    {"name":"Lusamine","class":"boss",      "specialty":"mixed",           "page":"Lusamine"},
]

TRAINER_DEFS: dict[str, list[dict]] = {
    "red":          _KANTO_GYMS_RBY + _KANTO_E4_RBY,
    "blue":         _KANTO_GYMS_RBY + _KANTO_E4_RBY,
    "yellow":       _KANTO_GYMS_RBY + _KANTO_E4_RBY,
    "firered":      _KANTO_GYMS_RBY + _KANTO_E4_RBY,
    "leafgreen":    _KANTO_GYMS_RBY + _KANTO_E4_RBY,
    "gold":         _JOHTO_GYMS + _JOHTO_E4,
    "silver":       _JOHTO_GYMS + _JOHTO_E4,
    "crystal":      _JOHTO_GYMS + _JOHTO_E4,
    "heartgold":    _JOHTO_GYMS + _KANTO_GYMS_HGSS + _JOHTO_E4,
    "soulsilver":   _JOHTO_GYMS + _KANTO_GYMS_HGSS + _JOHTO_E4,
    "ruby":         _HOENN_GYMS + _HOENN_E4_RS,
    "sapphire":     _HOENN_GYMS + _HOENN_E4_RS,
    "omega-ruby":   _HOENN_GYMS + _HOENN_E4_RS,
    "alpha-sapphire":_HOENN_GYMS + _HOENN_E4_RS,
    "emerald": [
        *[{**t, "name":"Juan", "page":"Juan"} if t["name"] == "Wallace" else t
          for t in _HOENN_GYMS],
        {"name":"Sidney",  "class":"elite_four","specialty":"dark",   "order":1,"page":"Sidney"},
        {"name":"Phoebe",  "class":"elite_four","specialty":"ghost",  "order":2,"page":"Phoebe"},
        {"name":"Glacia",  "class":"elite_four","specialty":"ice",    "order":3,"page":"Glacia"},
        {"name":"Drake",   "class":"elite_four","specialty":"dragon", "order":4,"page":"Drake (Elite Four)"},
        {"name":"Wallace", "class":"champion",  "specialty":"water",           "page":"Wallace"},
        {"name":"Brendan", "class":"rival",  "page":"Brendan",
         "rival_starter_map": {
             "torchic":"treecko","combusken":"treecko","blaziken":"treecko",
             "mudkip":"torchic","marshtomp":"torchic","swampert":"torchic",
             "treecko":"mudkip","grovyle":"mudkip","sceptile":"mudkip",
         }},
        {"name":"May",     "class":"rival",  "page":"May",
         "rival_starter_map": {
             "torchic":"treecko","combusken":"treecko","blaziken":"treecko",
             "mudkip":"torchic","marshtomp":"torchic","swampert":"torchic",
             "treecko":"mudkip","grovyle":"mudkip","sceptile":"mudkip",
         }},
    ],
    "diamond":      _SINNOH_GYMS + _SINNOH_E4,
    "pearl":        _SINNOH_GYMS + _SINNOH_E4,
    "platinum":     _SINNOH_GYMS + _SINNOH_E4,
    "black":        _UNOVA_GYMS_BW + _UNOVA_E4_BW,
    "white":        _UNOVA_GYMS_BW + _UNOVA_E4_BW,
    "black-2":      _UNOVA_GYMS_BW + _UNOVA_E4_BW,
    "white-2":      _UNOVA_GYMS_BW + _UNOVA_E4_BW,
    "x":            _KALOS_GYMS + _KALOS_E4,
    "y":            _KALOS_GYMS + _KALOS_E4,
    "sun":          _ALOLA_CAPTAINS + _ALOLA_E4,
    "moon":         _ALOLA_CAPTAINS + _ALOLA_E4,
    "ultra-sun":    _ALOLA_CAPTAINS + _ALOLA_E4,
    "ultra-moon":   _ALOLA_CAPTAINS + _ALOLA_E4,
}


# ── Static per-game data ───────────────────────────────────────────────────────

GAME_STATIC: dict[str, dict] = {
    "heartgold": {
        "starters": [
            {"pokemon":"chikorita","pokemon_id":152,"note":"Choose one at start"},
            {"pokemon":"cyndaquil","pokemon_id":155,"note":"Choose one at start"},
            {"pokemon":"totodile", "pokemon_id":158,"note":"Choose one at start"},
        ],
        "static_encounters": [
            {"pokemon":"gyarados",  "pokemon_id":130,"level":30,"location":"lake-of-rage","always_shiny":True,
             "note":"Red Gyarados — scripted shiny"},
            {"pokemon":"snorlax",   "pokemon_id":143,"level":50,"location":"route-11",
             "note":"Requires Poké Flute or Radio Poké Flute channel"},
            {"pokemon":"snorlax",   "pokemon_id":143,"level":50,"location":"route-12",
             "note":"Requires Poké Flute or Radio Poké Flute channel"},
            {"pokemon":"sudowoodo", "pokemon_id":185,"level":20,"location":"route-36",
             "note":"Requires Squirtbottle from Goldenrod flower shop"},
            # Ho-Oh: lv45 primary in HG, lv70 secondary in SS (both catchable in both versions)
            {"pokemon":"ho-oh","pokemon_id":250,"level":45,"location":"bell-tower",
             "version_native":"heartgold","note":"Requires Rainbow Wing; lv45 in HG, lv70 in SS"},
            {"pokemon":"ho-oh","pokemon_id":250,"level":70,"location":"bell-tower",
             "version_native":"soulsilver","note":"Secondary legendary in SS; requires Rainbow Wing"},
            # Lugia: lv45 primary in SS, lv70 secondary in HG
            {"pokemon":"lugia","pokemon_id":249,"level":45,"location":"whirl-islands",
             "version_native":"soulsilver","note":"Requires Silver Wing; lv45 in SS, lv70 in HG"},
            {"pokemon":"lugia","pokemon_id":249,"level":70,"location":"whirl-islands",
             "version_native":"heartgold","note":"Secondary legendary in HG; requires Silver Wing"},
            {"pokemon":"entei",   "pokemon_id":244,"level":40,"location":"johto","roaming":True,
             "note":"Roams Johto after the Burned Tower trio is released"},
            {"pokemon":"raikou",  "pokemon_id":243,"level":40,"location":"johto","roaming":True,
             "note":"Roams Johto after the Burned Tower trio is released"},
            {"pokemon":"suicune", "pokemon_id":245,"level":40,"location":"route-25",
             "note":"Appears at multiple fixed locations; final catchable encounter at Route 25"},
            # Groudon is HG-native; Kyogre is SS-native. Each requires trading the other
            # game's legend to Mr. Pokemon to receive the corresponding Orb.
            {"pokemon":"groudon","pokemon_id":383,"level":50,"location":"embedded-tower",
             "version_native":"heartgold","note":"Red Orb from Mr. Pokemon after showing Kyogre (SS)"},
            {"pokemon":"kyogre", "pokemon_id":382,"level":50,"location":"embedded-tower",
             "version_native":"soulsilver","note":"Blue Orb from Mr. Pokemon after showing Groudon (HG)"},
            {"pokemon":"rayquaza","pokemon_id":384,"level":50,"location":"embedded-tower",
             "note":"Appears after both Groudon and Kyogre are in the party simultaneously"},
            {"pokemon":"mewtwo",  "pokemon_id":150,"level":70,"location":"cerulean-cave","note":"Post-game Kanto"},
            {"pokemon":"articuno","pokemon_id":144,"level":50,"location":"seafoam-islands","note":"Post-game Kanto"},
            {"pokemon":"zapdos",  "pokemon_id":145,"level":50,"location":"power-plant","note":"Post-game Kanto"},
            {"pokemon":"moltres", "pokemon_id":146,"level":50,"location":"mt-silver","note":"Post-game"},
        ],
        "gift_pokemon": [
            {"pokemon":"togepi",  "pokemon_id":175,"level":1, "location":"mr-pokemons-house",
             "source":"Mr. Pokémon (Egg)","note":"Hatch the Mystery Egg received from Elm's errand"},
            {"pokemon":"eevee",   "pokemon_id":133,"level":5, "location":"goldenrod-city","source":"Bill"},
            {"pokemon":"tyrogue", "pokemon_id":236,"level":10,"location":"mt-mortar","source":"Karate King"},
            {"pokemon":"spearow", "pokemon_id":21, "level":20,"location":"route-35",
             "source":"Pokémon Ranger (holds Mail)"},
            {"pokemon":"dratini", "pokemon_id":147,"level":15,"location":"blackthorn-city",
             "source":"Dragon's Den quiz reward"},
            {"pokemon":"larvitar","pokemon_id":246,"level":1, "location":"mt-silver",
             "source":"Riley (Egg)","note":"Post-game"},
        ],
        "in_game_trades": [
            {"give_pokemon":"bellsprout","give_pokemon_id":69,
             "receive_pokemon":"onix",   "receive_pokemon_id":95, "receive_level":5,
             "npc":"Schoolboy Jack","location":"violet-city"},
            {"give_pokemon":"drowzee","give_pokemon_id":96,
             "receive_pokemon":"machop","receive_pokemon_id":66,  "receive_level":5,
             "npc":"Trainer","location":"goldenrod-city"},
            {"give_pokemon":"krabby","give_pokemon_id":98,
             "receive_pokemon":"voltorb","receive_pokemon_id":100,"receive_level":5,
             "npc":"Fisher","location":"olivine-city"},
        ],
    },

    "red": {
        "starters": [
            {"pokemon":"bulbasaur", "pokemon_id":1,"note":"Choose one at start"},
            {"pokemon":"charmander","pokemon_id":4,"note":"Choose one at start"},
            {"pokemon":"squirtle",  "pokemon_id":7,"note":"Choose one at start"},
        ],
        "static_encounters": [
            {"pokemon":"snorlax","pokemon_id":143,"level":30,"location":"route-12",
             "note":"Requires Poké Flute"},
            {"pokemon":"snorlax","pokemon_id":143,"level":30,"location":"route-16",
             "note":"Requires Poké Flute"},
            {"pokemon":"articuno","pokemon_id":144,"level":50,"location":"seafoam-islands"},
            {"pokemon":"zapdos",  "pokemon_id":145,"level":50,"location":"power-plant"},
            # Moltres is at Victory Road in RBY; it was moved to Mt. Ember in FRLG
            {"pokemon":"moltres",  "pokemon_id":146,"level":50,"location":"victory-road"},
            {"pokemon":"mewtwo",   "pokemon_id":150,"level":70,"location":"cerulean-cave"},
        ],
        "gift_pokemon": [
            # One-time room pickup (NOT a Game Corner prize — those are Porygon/Scyther/Pinsir)
            {"pokemon":"eevee",    "pokemon_id":133,"level":25,"location":"celadon-city",
             "source":"One-time pickup in Celadon Mansion top floor"},
            {"pokemon":"lapras",   "pokemon_id":131,"level":15,"location":"silph-co",
             "source":"NPC gift on 7F of Silph Co."},
            # Only one of Dome/Helix can be taken; both revived at Cinnabar Lab (not Pallet Town)
            {"pokemon":"aerodactyl","pokemon_id":142,"level":30,"location":"cinnabar-island",
             "source":"Old Amber (from scientist in Pewter Museum)"},
            {"pokemon":"omanyte",  "pokemon_id":138,"level":30,"location":"cinnabar-island",
             "source":"Dome Fossil — mutually exclusive with Helix Fossil"},
            {"pokemon":"kabuto",   "pokemon_id":140,"level":30,"location":"cinnabar-island",
             "source":"Helix Fossil — mutually exclusive with Dome Fossil"},
        ],
        "in_game_trades": [
            # Route 2 south gate: Nidoran-F for Nidoran-M nicknamed MARC
            {"give_pokemon":"nidoran-f","give_pokemon_id":29,
             "receive_pokemon":"nidoran-m","receive_pokemon_id":32,"receive_nickname":"MARC",
             "npc":"Trader","location":"route-2"},
            # Cerulean City: Poliwhirl for Jynx nicknamed LOLA
            {"give_pokemon":"poliwhirl","give_pokemon_id":61,
             "receive_pokemon":"jynx","receive_pokemon_id":124,"receive_nickname":"LOLA",
             "npc":"Girl","location":"cerulean-city"},
            # Vermilion City: Spearow for Farfetch'd nicknamed DUX
            {"give_pokemon":"spearow","give_pokemon_id":21,
             "receive_pokemon":"farfetchd","receive_pokemon_id":83,"receive_nickname":"DUX",
             "npc":"Sailor","location":"vermilion-city"},
        ],
    },
}
# Alias version pairs to the same static data dict
GAME_STATIC["soulsilver"] = GAME_STATIC["heartgold"]
GAME_STATIC["blue"]       = GAME_STATIC["red"]
GAME_STATIC["yellow"]     = GAME_STATIC["red"]
GAME_STATIC["firered"]    = GAME_STATIC["red"]
GAME_STATIC["leafgreen"]  = GAME_STATIC["red"]


# ── Route unlock order ─────────────────────────────────────────────────────────
# "badges"  = number of badges already earned before this area is first reachable
# "hm"      = HM move required to enter (move slug, e.g. "surf")
# "event"   = short story-event key (informational; app maps these to display text)

def _r(order: int, location: str, display: str, *,
       badges: int = 0, hm: str | None = None,
       event: str | None = None, note: str | None = None) -> dict:
    entry: dict = {
        "order":        order,
        "location":     location,
        "display_name": display,
        "prerequisites": {"badges": badges, "hm": hm, "event": event},
    }
    if note:
        entry["note"] = note
    return entry


ROUTE_ORDER: dict[str, list[dict]] = {
    # ── HeartGold / SoulSilver ──────────────────────────────────────────────
    "heartgold": [
        _r(1,  "new-bark-town",    "New Bark Town"),
        _r(2,  "route-29",         "Route 29"),
        _r(3,  "cherrygrove-city", "Cherrygrove City"),
        _r(4,  "route-30",         "Route 30"),
        _r(5,  "route-31",         "Route 31"),
        _r(6,  "violet-city",      "Violet City",        event="gym1_zephyr"),
        _r(7,  "ruins-of-alph",    "Ruins of Alph",      note="Entrance via Route 32; full access needs Rock Smash"),
        _r(8,  "route-32",         "Route 32"),
        _r(9,  "union-cave",       "Union Cave",         note="Lower floors require Surf"),
        _r(10, "route-33",         "Route 33"),
        _r(11, "slowpoke-well",    "Slowpoke Well",      event="defeat_rockets_slowpoke_well"),
        _r(12, "azalea-town",      "Azalea Town",        event="gym2_hive"),
        # HM01 Cut obtained from the Charcoal Man's apprentice inside Ilex Forest
        _r(13, "ilex-forest",      "Ilex Forest",        hm="cut", event="gym2_hive"),
        _r(14, "route-34",         "Route 34",           hm="cut"),
        _r(15, "goldenrod-city",   "Goldenrod City",     event="gym3_plain"),
        _r(16, "route-35",         "Route 35"),
        _r(17, "national-park",    "National Park"),
        # Sudowoodo blocks Route 36; Squirtbottle from Goldenrod flower shop clears it
        _r(18, "route-36",         "Route 36",           event="squirtbottle_sudowoodo"),
        _r(19, "route-37",         "Route 37"),
        _r(20, "ecruteak-city",    "Ecruteak City",      event="gym4_fog"),
        # HM03 Surf given by Kimono Girls in the Ecruteak Dance Theater
        _r(21, "route-38",         "Route 38"),
        _r(22, "route-39",         "Route 39"),
        _r(23, "olivine-city",     "Olivine City",       note="Jasmine at lighthouse until SecretPotion delivered"),
        _r(24, "route-40",         "Route 40",           hm="surf"),
        _r(25, "route-41",         "Route 41",           hm="surf"),
        _r(26, "whirl-islands",    "Whirl Islands",      hm="surf", note="Inner floors need Whirlpool + Strength"),
        _r(27, "cianwood-city",    "Cianwood City",      hm="surf", note="HM02 Fly from woman near gym; Storm Badge enables Fly"),
        # Return to Olivine after obtaining SecretPotion from Cianwood pharmacy
        _r(28, "olivine-city",     "Olivine City (Gym)", badges=5, event="gym6_mineral",
           note="Jasmine returns to gym after SecretPotion delivered to Ampharos"),
        _r(29, "route-42",         "Route 42",           note="Ecruteak↔Mahogany; Mt. Mortar entrance on this route"),
        _r(30, "mt-mortar",        "Mt. Mortar",         hm="surf", note="Tyrogue gift from Karate King inside"),
        _r(31, "route-43",         "Route 43"),
        _r(32, "lake-of-rage",     "Lake of Rage",       event="red_gyarados", note="Red Gyarados; Lance appears"),
        _r(33, "mahogany-town",    "Mahogany Town",      event="defeat_rockets_mahogany"),
        _r(34, "team-rocket-hq",   "Team Rocket HQ",     event="defeat_rockets_mahogany"),
        _r(35, "route-44",         "Route 44",           badges=7),
        _r(36, "ice-path",         "Ice Path",           badges=7, hm="strength", note="Strength for boulder puzzles"),
        _r(37, "blackthorn-city",  "Blackthorn City",    event="gym8_rising"),
        _r(38, "dragons-den",      "Dragon's Den",       event="gym8_rising", note="Dratini gift from quiz"),
        _r(39, "route-45",         "Route 45",           note="Connects Blackthorn south toward New Bark Town area"),
        _r(40, "route-46",         "Route 46"),
        # Radio Tower Rockets must be defeated before the route to Kanto is cleared
        _r(41, "route-27",         "Route 27",           badges=8, hm="surf"),
        _r(42, "route-26",         "Route 26",           badges=8, hm="surf"),
        _r(43, "pokemon-league",   "Pokémon League",     badges=8,
           note="Johto E4: Will → Koga → Bruno → Karen → Lance"),
        # ── Kanto (post-game) ──────────────────────────────────────────────
        _r(44, "pallet-town",      "Pallet Town",        badges=8, event="beat_johto_champion",
           note="Post-game Kanto begins here"),
        _r(45, "route-1",          "Route 1",            badges=8),
        _r(46, "viridian-city",    "Viridian City",      badges=8),
        _r(47, "route-2",          "Route 2",            badges=8),
        _r(48, "pewter-city",      "Pewter City",        badges=8,  note="Gym 9: Brock (Rock)"),
        _r(49, "route-3",          "Route 3",            badges=9),
        _r(50, "mt-moon",          "Mt. Moon",           badges=9),
        _r(51, "route-4",          "Route 4",            badges=9),
        _r(52, "cerulean-city",    "Cerulean City",      badges=9,  note="Gym 10: Misty (Water)"),
        _r(53, "route-24",         "Route 24",           badges=10),
        _r(54, "route-25",         "Route 25",           badges=10, note="Suicune final encounter here"),
        _r(55, "route-5",          "Route 5",            badges=10),
        _r(56, "route-6",          "Route 6",            badges=10),
        _r(57, "vermilion-city",   "Vermilion City",     badges=10, note="Gym 11: Lt. Surge (Electric)"),
        _r(58, "route-11",         "Route 11",           badges=11, note="Snorlax — needs Poké Flute/Radio"),
        _r(59, "route-12",         "Route 12",           badges=11, note="Snorlax — needs Poké Flute/Radio"),
        _r(60, "route-13",         "Route 13",           badges=11),
        _r(61, "route-14",         "Route 14",           badges=11),
        _r(62, "route-15",         "Route 15",           badges=11),
        _r(63, "fuchsia-city",     "Fuchsia City",       badges=11, note="Gym 13: Janine (Poison)"),
        _r(64, "celadon-city",     "Celadon City",       badges=11, note="Gym 12: Erika (Grass)"),
        _r(65, "route-16",         "Route 16",           badges=13),
        _r(66, "route-17",         "Route 17",           badges=13),
        _r(67, "route-18",         "Route 18",           badges=13),
        _r(68, "route-7",          "Route 7",            badges=12),
        _r(69, "route-8",          "Route 8",            badges=12),
        _r(70, "lavender-town",    "Lavender Town",      badges=12),
        _r(71, "rock-tunnel",      "Rock Tunnel",        badges=12),
        _r(72, "route-9",          "Route 9",            badges=12),
        _r(73, "route-10",         "Route 10",           badges=12),
        _r(74, "power-plant",      "Power Plant",        badges=12, note="Zapdos lv50 here"),
        _r(75, "saffron-city",     "Saffron City",       badges=12, note="Gym 14: Sabrina (Psychic)"),
        _r(76, "route-19",         "Route 19",           badges=13, hm="surf"),
        _r(77, "route-20",         "Route 20",           badges=13, hm="surf"),
        _r(78, "seafoam-islands",  "Seafoam Islands",    badges=13, hm="surf", note="Articuno lv50 here"),
        _r(79, "cinnabar-island",  "Cinnabar Island",    badges=13, hm="surf",
           note="Gym 15: Blaine (Fire) — note: Moltres is at Mt. Silver in HGSS, not here"),
        _r(80, "route-21",         "Route 21",           badges=15, hm="surf"),
        _r(81, "viridian-city",    "Viridian City (Gym)",badges=15,
           note="Gym 16: Blue — requires all 15 other Kanto badges"),
        _r(82, "mt-silver",        "Mt. Silver",         badges=16, hm="rock-climb",
           note="Moltres lv50 here; Red (final boss) at the summit"),
        _r(83, "cerulean-cave",    "Cerulean Cave",      badges=16, hm="surf", note="Mewtwo lv70"),
    ],

    # ── Red / Blue / Yellow ─────────────────────────────────────────────────
    "red": [
        _r(1,  "pallet-town",     "Pallet Town"),
        _r(2,  "route-1",         "Route 1"),
        _r(3,  "viridian-city",   "Viridian City"),
        _r(4,  "route-2",         "Route 2"),
        _r(5,  "viridian-forest", "Viridian Forest"),
        _r(6,  "pewter-city",     "Pewter City",        event="gym1_boulder"),
        _r(7,  "route-3",         "Route 3",            badges=1),
        _r(8,  "mt-moon",         "Mt. Moon",           badges=1),
        _r(9,  "route-4",         "Route 4",            badges=1),
        _r(10, "cerulean-city",   "Cerulean City",      event="gym2_cascade"),
        _r(11, "route-24",        "Route 24",           badges=2),
        _r(12, "route-25",        "Route 25",           badges=2),
        _r(13, "route-5",         "Route 5",            badges=2),
        _r(14, "route-6",         "Route 6",            badges=2),
        _r(15, "vermilion-city",  "Vermilion City",     event="gym3_thunder"),
        _r(16, "ss-anne",         "S.S. Anne",          badges=2, note="HM01 Cut from the Captain"),
        _r(17, "route-11",        "Route 11",           hm="cut"),
        _r(18, "route-12",        "Route 12",           hm="cut", note="Snorlax — needs Poké Flute"),
        _r(19, "route-13",        "Route 13"),
        _r(20, "route-14",        "Route 14"),
        _r(21, "route-15",        "Route 15"),
        _r(22, "route-9",         "Route 9",            hm="cut"),
        _r(23, "route-10",        "Route 10",           hm="cut"),
        _r(24, "rock-tunnel",     "Rock Tunnel"),
        _r(25, "lavender-town",   "Lavender Town"),
        _r(26, "route-8",         "Route 8"),
        _r(27, "route-7",         "Route 7"),
        _r(28, "celadon-city",    "Celadon City",       event="gym4_rainbow"),
        _r(29, "route-16",        "Route 16",           hm="cut", note="Snorlax — needs Poké Flute"),
        _r(30, "route-17",        "Route 17"),
        _r(31, "route-18",        "Route 18"),
        _r(32, "fuchsia-city",    "Fuchsia City",       event="gym5_soul"),
        _r(33, "route-19",        "Route 19",           hm="surf"),
        _r(34, "route-20",        "Route 20",           hm="surf"),
        _r(35, "seafoam-islands", "Seafoam Islands",    hm="surf", note="Articuno lv50 here"),
        _r(36, "cinnabar-island", "Cinnabar Island",    hm="surf", event="gym7_volcano"),
        _r(37, "route-21",        "Route 21",           hm="surf"),
        _r(38, "saffron-city",    "Saffron City",       event="gym6_marsh"),
        _r(39, "power-plant",     "Power Plant",        hm="surf", note="Zapdos lv50 here"),
        _r(40, "route-22",        "Route 22",           badges=7),
        _r(41, "route-23",        "Route 23",           badges=7),
        _r(42, "victory-road",    "Victory Road",       badges=7, hm="strength",
           note="Moltres lv50 inside — NOT at Mt. Ember (that's FRLG only)"),
        _r(43, "viridian-city",   "Viridian City (Gym)",badges=7, note="Gym 8: Giovanni (Ground)"),
        _r(44, "pokemon-league",  "Pokémon League",     badges=8,
           note="E4: Lorelei → Bruno → Agatha → Lance → Blue"),
        _r(45, "cerulean-cave",   "Cerulean Cave",      badges=8, hm="surf", note="Mewtwo lv70"),
    ],

    # ── Hoenn (Ruby / Sapphire / Emerald / ORAS) ────────────────────────────
    "ruby": [
        _r(1,  "littleroot-town",  "Littleroot Town"),
        _r(2,  "route-101",        "Route 101"),
        _r(3,  "oldale-town",      "Oldale Town"),
        _r(4,  "route-103",        "Route 103"),
        _r(5,  "route-102",        "Route 102"),
        _r(6,  "petalburg-city",   "Petalburg City"),
        _r(7,  "route-104",        "Route 104"),
        _r(8,  "petalburg-woods",  "Petalburg Woods"),
        _r(9,  "rustboro-city",    "Rustboro City",       event="gym1_stone"),
        _r(10, "route-116",        "Route 116",           badges=1),
        _r(11, "rusturf-tunnel",   "Rusturf Tunnel",      hm="rock-smash"),
        _r(12, "route-105",        "Route 105",           hm="surf"),
        _r(13, "route-106",        "Route 106",           hm="surf"),
        _r(14, "dewford-town",     "Dewford Town",        event="gym2_knuckle"),
        _r(15, "granite-cave",     "Granite Cave"),
        _r(16, "route-107",        "Route 107",           hm="surf"),
        _r(17, "route-108",        "Route 108",           hm="surf"),
        _r(18, "route-109",        "Route 109",           hm="surf"),
        _r(19, "slateport-city",   "Slateport City"),
        _r(20, "route-110",        "Route 110"),
        _r(21, "mauville-city",    "Mauville City",       event="gym3_dynamo"),
        _r(22, "route-117",        "Route 117",           badges=3),
        _r(23, "route-111",        "Route 111",           badges=3),
        _r(24, "route-112",        "Route 112",           badges=3),
        _r(25, "lavaridge-town",   "Lavaridge Town",      event="gym4_heat"),
        _r(26, "petalburg-city",   "Petalburg City (Gym)",badges=4, event="gym5_balance"),
        _r(27, "route-118",        "Route 118",           badges=5, hm="surf"),
        _r(28, "route-119",        "Route 119",           badges=5, hm="surf"),
        _r(29, "fortree-city",     "Fortree City",        event="gym6_feather"),
        _r(30, "route-120",        "Route 120",           badges=6),
        _r(31, "route-121",        "Route 121",           badges=6),
        _r(32, "lilycove-city",    "Lilycove City",       badges=6),
        _r(33, "route-122",        "Route 122",           hm="surf"),
        _r(34, "mt-pyre",          "Mt. Pyre",            hm="surf"),
        _r(35, "route-123",        "Route 123",           badges=6),
        _r(36, "mossdeep-city",    "Mossdeep City",       event="gym7_mind"),
        _r(37, "route-124",        "Route 124",           hm="surf"),
        _r(38, "route-125",        "Route 125",           hm="surf"),
        _r(39, "route-126",        "Route 126",           hm="surf"),
        _r(40, "sootopolis-city",  "Sootopolis City",     hm="surf", event="gym8_rain"),
        _r(41, "route-127",        "Route 127",           hm="surf"),
        _r(42, "route-128",        "Route 128",           hm="surf"),
        _r(43, "route-129",        "Route 129",           hm="surf"),
        _r(44, "route-130",        "Route 130",           hm="surf"),
        _r(45, "route-131",        "Route 131",           hm="surf"),
        _r(46, "pacifidlog-town",  "Pacifidlog Town",     hm="surf"),
        _r(47, "ever-grande-city", "Ever Grande City",    hm="surf"),
        _r(48, "victory-road",     "Victory Road",        badges=8, hm="strength"),
        _r(49, "pokemon-league",   "Pokémon League",      badges=8,
           note="E4: Sidney → Phoebe → Glacia → Drake → Steven"),
        _r(50, "sky-pillar",       "Sky Pillar",          hm="surf", note="Rayquaza lv70 (post-story)"),
    ],

    # ── Sinnoh (Diamond / Pearl / Platinum) ─────────────────────────────────
    "diamond": [
        _r(1,  "twinleaf-town",    "Twinleaf Town"),
        _r(2,  "route-201",        "Route 201"),
        _r(3,  "sandgem-town",     "Sandgem Town"),
        _r(4,  "route-202",        "Route 202"),
        _r(5,  "jubilife-city",    "Jubilife City"),
        _r(6,  "route-203",        "Route 203"),
        _r(7,  "oreburgh-gate",    "Oreburgh Gate"),
        _r(8,  "oreburgh-city",    "Oreburgh City",       event="gym1_coal"),
        _r(9,  "oreburgh-mine",    "Oreburgh Mine"),
        _r(10, "route-204",        "Route 204"),
        _r(11, "ravaged-path",     "Ravaged Path",        hm="rock-smash"),
        _r(12, "floaroma-town",    "Floaroma Town"),
        _r(13, "route-205",        "Route 205"),
        _r(14, "eterna-city",      "Eterna City",         event="gym2_forest"),
        _r(15, "eterna-forest",    "Eterna Forest"),
        _r(16, "route-206",        "Route 206",           hm="cut"),
        _r(17, "route-207",        "Route 207"),
        _r(18, "mt-coronet",       "Mt. Coronet",         note="Accessible early; full traverse unlocked later"),
        _r(19, "route-208",        "Route 208",           badges=2),
        _r(20, "hearthome-city",   "Hearthome City",      badges=2),
        _r(21, "route-209",        "Route 209",           badges=2),
        _r(22, "solaceon-town",    "Solaceon Town",       badges=2),
        _r(23, "route-210",        "Route 210",           badges=2),
        _r(24, "route-215",        "Route 215",           badges=2),
        _r(25, "veilstone-city",   "Veilstone City",      event="gym3_cobble"),
        _r(26, "route-214",        "Route 214",           badges=3),
        _r(27, "pastoria-city",    "Pastoria City",       event="gym4_fen"),
        _r(28, "route-212",        "Route 212",           badges=4, hm="surf"),
        _r(29, "route-213",        "Route 213",           badges=4, hm="surf"),
        _r(30, "hearthome-city",   "Hearthome City (Gym)",badges=4, event="gym5_relic"),
        _r(31, "route-218",        "Route 218",           hm="surf"),
        _r(32, "canalave-city",    "Canalave City",       hm="surf", event="gym6_mine"),
        _r(33, "route-216",        "Route 216",           badges=6),
        _r(34, "route-217",        "Route 217",           badges=6),
        _r(35, "snowpoint-city",   "Snowpoint City",      event="gym7_icicle"),
        _r(36, "lake-acuity",      "Lake Acuity",         badges=7),
        _r(37, "route-222",        "Route 222",           badges=7),
        _r(38, "sunyshore-city",   "Sunyshore City",      event="gym8_beacon"),
        _r(39, "route-223",        "Route 223",           badges=8, hm="surf"),
        _r(40, "victory-road",     "Victory Road",        badges=8, hm="strength"),
        _r(41, "pokemon-league",   "Pokémon League",      badges=8,
           note="E4: Aaron → Bertha → Flint → Lucian → Cynthia"),
    ],

    # ── Unova (Black / White) ────────────────────────────────────────────────
    "black": [
        _r(1,  "nuvema-town",       "Nuvema Town"),
        _r(2,  "route-1",           "Route 1"),
        _r(3,  "accumula-town",     "Accumula Town"),
        _r(4,  "route-2",           "Route 2"),
        _r(5,  "striaton-city",     "Striaton City",        event="gym1_trio",
           note="Gym 1: Cilan/Chili/Cress (Grass/Fire/Water — chosen by starter)"),
        _r(6,  "dreamyard",         "Dreamyard",            badges=1),
        _r(7,  "route-3",           "Route 3",              badges=1),
        _r(8,  "wellspring-cave",   "Wellspring Cave",      badges=1),
        _r(9,  "route-4",           "Route 4 (west)",       badges=1,
           note="Desert area west of Nacrene"),
        _r(10, "desert-resort",     "Desert Resort",        badges=1),
        _r(11, "relic-castle",      "Relic Castle",         badges=1,
           note="Inside Desert Resort"),
        _r(12, "nacrene-city",      "Nacrene City",         event="gym2_basic",
           note="Gym 2: Lenora (Normal)"),
        _r(13, "pinwheel-forest",   "Pinwheel Forest"),
        _r(14, "skyarrow-bridge",   "Skyarrow Bridge"),
        _r(15, "castelia-city",     "Castelia City",        event="gym3_insect",
           note="Gym 3: Burgh (Bug)"),
        _r(16, "castelia-sewers",   "Castelia Sewers",      badges=3),
        _r(17, "route-4",           "Route 4 (east)",       badges=3,
           note="East of Castelia heading to Nimbasa"),
        _r(18, "nimbasa-city",      "Nimbasa City",         event="gym4_bolt",
           note="Gym 4: Elesa (Electric)"),
        _r(19, "route-16",          "Route 16",             badges=4),
        _r(20, "lostlorn-forest",   "Lostlorn Forest",      badges=4),
        _r(21, "route-5",           "Route 5",              badges=4),
        _r(22, "driftveil-drawbridge","Driftveil Drawbridge",badges=4),
        _r(23, "driftveil-city",    "Driftveil City",       event="gym5_quake",
           note="Gym 5: Clay (Ground)"),
        _r(24, "cold-storage",      "Cold Storage",         badges=5),
        _r(25, "route-6",           "Route 6",              badges=5),
        _r(26, "chargestone-cave",  "Chargestone Cave",     badges=5),
        _r(27, "mistralton-city",   "Mistralton City",      event="gym6_jet",
           note="Gym 6: Skyla (Flying)"),
        _r(28, "celestial-tower",   "Celestial Tower",      badges=6),
        _r(29, "route-7",           "Route 7",              badges=6),
        _r(30, "twist-mountain",    "Twist Mountain",       badges=6),
        _r(31, "icirrus-city",      "Icirrus City",         event="gym7_freeze",
           note="Gym 7: Brycen (Ice)"),
        _r(32, "dragonspiral-tower","Dragonspiral Tower",   badges=7),
        _r(33, "route-8",           "Route 8",              badges=7),
        _r(34, "moor-of-icirrus",   "Moor of Icirrus",      badges=7),
        _r(35, "lacunosa-town",     "Lacunosa Town",        badges=7),
        _r(36, "route-9",           "Route 9",              badges=7),
        _r(37, "opelucid-city",     "Opelucid City",        event="gym8_legend",
           note="Gym 8: Drayden (Black) / Iris (White) — Dragon"),
        _r(38, "route-10",          "Route 10",             badges=8),
        _r(39, "victory-road",      "Victory Road",         badges=8, hm="strength"),
        _r(40, "pokemon-league",    "Pokémon League",       badges=8,
           note="E4: Shauntal → Grimsley → Caitlin → Marshal → Alder"),
    ],

    # ── Unova (Black 2 / White 2) ────────────────────────────────────────────
    "black-2": [
        _r(1,  "aspertia-city",     "Aspertia City",        event="gym1_aspertia",
           note="Gym 1: Cheren (Normal)"),
        _r(2,  "route-19",          "Route 19"),
        _r(3,  "floccesy-town",     "Floccesy Town"),
        _r(4,  "floccesy-ranch",    "Floccesy Ranch"),
        _r(5,  "route-20",          "Route 20",             badges=1),
        _r(6,  "virbank-city",      "Virbank City",         event="gym2_virbank",
           note="Gym 2: Roxie (Poison)"),
        _r(7,  "virbank-complex",   "Virbank Complex",      badges=2),
        _r(8,  "castelia-city",     "Castelia City",        event="gym3_insect",
           note="Gym 3: Burgh (Bug)"),
        _r(9,  "castelia-sewers",   "Castelia Sewers",      badges=3),
        _r(10, "route-4",           "Route 4",              badges=3),
        _r(11, "desert-resort",     "Desert Resort",        badges=3),
        _r(12, "nimbasa-city",      "Nimbasa City",         event="gym4_bolt",
           note="Gym 4: Elesa (Electric)"),
        _r(13, "route-16",          "Route 16",             badges=4),
        _r(14, "lostlorn-forest",   "Lostlorn Forest",      badges=4),
        _r(15, "route-5",           "Route 5",              badges=4),
        _r(16, "driftveil-drawbridge","Driftveil Drawbridge",badges=4),
        _r(17, "driftveil-city",    "Driftveil City",       event="gym5_quake",
           note="Gym 5: Clay (Ground)"),
        _r(18, "route-6",           "Route 6",              badges=5),
        _r(19, "chargestone-cave",  "Chargestone Cave",     badges=5),
        _r(20, "mistralton-city",   "Mistralton City",      event="gym6_jet",
           note="Gym 6: Skyla (Flying)"),
        _r(21, "celestial-tower",   "Celestial Tower",      badges=6),
        _r(22, "route-7",           "Route 7",              badges=6),
        _r(23, "twist-mountain",    "Twist Mountain",       badges=6),
        _r(24, "icirrus-city",      "Icirrus City",         badges=6,
           note="No gym in BW2; Brycen became a movie star"),
        _r(25, "route-8",           "Route 8",              badges=6),
        _r(26, "moor-of-icirrus",   "Moor of Icirrus",      badges=6),
        _r(27, "lacunosa-town",     "Lacunosa Town",        badges=6),
        _r(28, "route-9",           "Route 9 (west)",       badges=6),
        _r(29, "opelucid-city",     "Opelucid City",        event="gym7_legend",
           note="Gym 7: Drayden (Dragon)"),
        _r(30, "route-9",           "Route 9 (east)",       badges=7),
        _r(31, "seaside-cave",      "Seaside Cave",         badges=7),
        _r(32, "humilau-city",      "Humilau City",         event="gym8_wave",
           note="Gym 8: Marlon (Water)"),
        _r(33, "marine-tube",       "Marine Tube",          badges=8),
        _r(34, "undella-town",      "Undella Town",         badges=8),
        _r(35, "route-13",          "Route 13",             badges=8),
        _r(36, "giant-chasm",       "Giant Chasm",          badges=8),
        _r(37, "route-22",          "Route 22",             badges=8),
        _r(38, "route-23",          "Route 23",             badges=8, hm="strength"),
        _r(39, "victory-road",      "Victory Road",         badges=8, hm="strength"),
        _r(40, "pokemon-league",    "Pokémon League",       badges=8,
           note="E4: Shauntal → Grimsley → Caitlin → Marshal → Iris"),
    ],

    # ── Kalos (X / Y) ────────────────────────────────────────────────────────
    "x": [
        _r(1,  "vaniville-town",    "Vaniville Town"),
        _r(2,  "route-1",           "Route 1"),
        _r(3,  "aquacorde-town",    "Aquacorde Town"),
        _r(4,  "route-2",           "Route 2"),
        _r(5,  "santalune-forest",  "Santalune Forest"),
        _r(6,  "santalune-city",    "Santalune City",       event="gym1_bug",
           note="Gym 1: Viola (Bug)"),
        _r(7,  "route-3",           "Route 3",              badges=1),
        _r(8,  "lumiose-city",      "Lumiose City (partial)",badges=1,
           note="Full access after defeating Clemont"),
        _r(9,  "route-4",           "Route 4",              badges=1),
        _r(10, "route-22",          "Route 22",             badges=1),
        _r(11, "camphrier-town",    "Camphrier Town",       badges=1),
        _r(12, "route-5",           "Route 5",              badges=1),
        _r(13, "connecting-cave",   "Connecting Cave",      badges=1),
        _r(14, "route-6",           "Route 6",              badges=1),
        _r(15, "parfum-palace",     "Parfum Palace",        badges=1),
        _r(16, "route-7",           "Route 7",              badges=1),
        _r(17, "glittering-cave",   "Glittering Cave",      badges=1),
        _r(18, "route-8",           "Route 8",              badges=1),
        _r(19, "ambrette-town",     "Ambrette Town",        badges=1),
        _r(20, "cyllage-city",      "Cyllage City",         event="gym2_cliff",
           note="Gym 2: Grant (Rock)"),
        _r(21, "route-9",           "Route 9",              badges=2),
        _r(22, "spiky-passage",     "Spiky Passage",        badges=2),
        _r(23, "geosenge-town",     "Geosenge Town",        badges=2),
        _r(24, "route-10",          "Route 10",             badges=2),
        _r(25, "route-11",          "Route 11",             badges=2),
        _r(26, "shalour-city",      "Shalour City",         event="gym3_rumble",
           note="Gym 3: Korrina (Fighting)"),
        _r(27, "tower-of-mastery",  "Tower of Mastery",     badges=3),
        _r(28, "route-12",          "Route 12",             badges=3),
        _r(29, "azure-bay",         "Azure Bay",            badges=3),
        _r(30, "coumarine-city",    "Coumarine City",       event="gym4_grass",
           note="Gym 4: Ramos (Grass)"),
        _r(31, "route-13",          "Route 13",             badges=4),
        _r(32, "lumiose-city",      "Lumiose City (Gym)",   event="gym5_voltage",
           note="Gym 5: Clemont (Electric)"),
        _r(33, "route-14",          "Route 14",             badges=5),
        _r(34, "laverre-city",      "Laverre City",         event="gym6_fairy",
           note="Gym 6: Valerie (Fairy)"),
        _r(35, "poke-ball-factory", "Poké Ball Factory",    badges=6),
        _r(36, "route-15",          "Route 15",             badges=6),
        _r(37, "route-16",          "Route 16",             badges=6),
        _r(38, "dendemille-town",   "Dendemille Town",      badges=6),
        _r(39, "route-17",          "Route 17",             badges=6),
        _r(40, "anistar-city",      "Anistar City",         event="gym7_psychic",
           note="Gym 7: Olympia (Psychic)"),
        _r(41, "route-18",          "Route 18",             badges=7),
        _r(42, "terminus-cave",     "Terminus Cave",        badges=7),
        _r(43, "couriway-town",     "Couriway Town",        badges=7),
        _r(44, "snowbelle-city",    "Snowbelle City",       event="gym8_iceberg",
           note="Gym 8: Wulfric (Ice)"),
        _r(45, "route-20",          "Route 20 (Winding Woods)",badges=8),
        _r(46, "victory-road",      "Victory Road",         badges=8),
        _r(47, "pokemon-league",    "Pokémon League",       badges=8,
           note="E4: Malva → Siebold → Wikstrom → Drasna → Diantha"),
    ],

    # ── Alola (Sun / Moon) ───────────────────────────────────────────────────
    "sun": [
        _r(1,  "iki-town",          "Iki Town"),
        _r(2,  "route-1",           "Route 1 (south)"),
        _r(3,  "route-1",           "Route 1 (north)",      event="trial0_ilima",
           note="Captain Ilima's trial (Normal)"),
        _r(4,  "trainer-school",    "Trainer School"),
        _r(5,  "hauoli-city",       "Hau'oli City"),
        _r(6,  "route-2",           "Route 2"),
        _r(7,  "berry-fields",      "Berry Fields"),
        _r(8,  "route-3",           "Route 3"),
        _r(9,  "melemele-sea",      "Melemele Sea",         hm=None,
           note="No HMs in Gen 7; Ride Pokémon used instead"),
        _r(10, "kala-e-bay",        "Kala'e Bay"),
        _r(11, "ten-carat-hill",    "Ten Carat Hill"),
        _r(12, "melemele-grand-trial","Melemele Grand Trial",event="grand_trial1_hala",
           note="Kahuna Hala (Fighting)"),
        _r(13, "route-4",           "Route 4"),
        _r(14, "paniola-town",      "Paniola Town"),
        _r(15, "paniola-ranch",     "Paniola Ranch"),
        _r(16, "route-5",           "Route 5"),
        _r(17, "brooklet-hill",     "Brooklet Hill",        event="trial1_lana",
           note="Trial Captain Lana (Water) — Totem Wishiwashi"),
        _r(18, "route-6",           "Route 6"),
        _r(19, "royal-avenue",      "Royal Avenue"),
        _r(20, "route-7",           "Route 7"),
        _r(21, "wela-volcano-park", "Wela Volcano Park",    event="trial2_kiawe",
           note="Trial Captain Kiawe (Fire) — Totem Marowak"),
        _r(22, "route-8",           "Route 8"),
        _r(23, "lush-jungle",       "Lush Jungle",          event="trial3_mallow",
           note="Trial Captain Mallow (Grass) — Totem Lurantis"),
        _r(24, "route-9",           "Route 9"),
        _r(25, "konikoni-city",     "Konikoni City"),
        _r(26, "ruins-of-life",     "Ruins of Life"),
        _r(27, "akala-grand-trial", "Akala Grand Trial",    event="grand_trial2_olivia",
           note="Kahuna Olivia (Rock)"),
        _r(28, "route-10",          "Route 10"),
        _r(29, "route-11",          "Route 11"),
        _r(30, "aether-house",      "Aether House"),
        _r(31, "route-12",          "Route 12"),
        _r(32, "blush-mountain",    "Blush Mountain"),
        _r(33, "route-13",          "Route 13"),
        _r(34, "tapu-village",      "Tapu Village"),
        _r(35, "route-14",          "Route 14"),
        _r(36, "route-15",          "Route 15"),
        _r(37, "ula-ula-meadow",    "Ula'ula Meadow"),
        _r(38, "route-16",          "Route 16"),
        _r(39, "malie-city",        "Malie City"),
        _r(40, "mount-hokulani",    "Mount Hokulani",       event="trial4_sophocles",
           note="Trial Captain Sophocles (Electric) — Totem Vikavolt"),
        _r(41, "route-17",          "Route 17"),
        _r(42, "po-town",           "Po Town"),
        _r(43, "aether-paradise",   "Aether Paradise",      event="aether_story"),
        _r(44, "ula-ula-grand-trial","Ula'ula Grand Trial",  event="grand_trial3_nanu",
           note="Kahuna Nanu (Dark)"),
        _r(45, "route-14",          "Route 14 (south)"),
        _r(46, "seafolk-village",   "Seafolk Village"),
        _r(47, "poni-wilds",        "Poni Wilds"),
        _r(48, "ancient-poni-path", "Ancient Poni Path"),
        _r(49, "poni-plains",       "Poni Plains"),
        _r(50, "vast-poni-canyon",  "Vast Poni Canyon",     event="trial5_hapu",
           note="Trial: Hapu (Ground) — leads to Grand Trial"),
        _r(51, "poni-grand-trial",  "Poni Grand Trial",     event="grand_trial4_hapu",
           note="Kahuna Hapu (Ground)"),
        _r(52, "altar-of-sunne",    "Altar of the Sunne/Moone", event="story_legendary",
           note="Cosmog evolves; Solgaleo (Sun) / Lunala (Moon) encounter"),
        _r(53, "mount-lanakila",    "Mount Lanakila",       event="story_complete"),
        _r(54, "pokemon-league",    "Pokémon League",
           note="E4: Hala → Olivia → Acerola → Kahili → Professor Kukui"),
    ],

    # ── Ultra Alola (Ultra Sun / Ultra Moon) ─────────────────────────────────
    # Core route order matches Sun/Moon; Ultra adds Wormhole encounters and
    # a different post-game but the main island challenge path is identical.
    "ultra-sun": [
        _r(1,  "iki-town",          "Iki Town"),
        _r(2,  "route-1",           "Route 1 (south)"),
        _r(3,  "route-1",           "Route 1 (north)",      event="trial0_ilima",
           note="Captain Ilima's trial (Normal)"),
        _r(4,  "trainer-school",    "Trainer School"),
        _r(5,  "hauoli-city",       "Hau'oli City"),
        _r(6,  "route-2",           "Route 2"),
        _r(7,  "berry-fields",      "Berry Fields"),
        _r(8,  "route-3",           "Route 3"),
        _r(9,  "melemele-sea",      "Melemele Sea"),
        _r(10, "kala-e-bay",        "Kala'e Bay"),
        _r(11, "ten-carat-hill",    "Ten Carat Hill"),
        _r(12, "melemele-grand-trial","Melemele Grand Trial",event="grand_trial1_hala",
           note="Kahuna Hala (Fighting)"),
        _r(13, "route-4",           "Route 4"),
        _r(14, "paniola-town",      "Paniola Town"),
        _r(15, "paniola-ranch",     "Paniola Ranch"),
        _r(16, "route-5",           "Route 5"),
        _r(17, "brooklet-hill",     "Brooklet Hill",        event="trial1_lana",
           note="Trial Captain Lana (Water) — Totem Araquanid (USUM)"),
        _r(18, "route-6",           "Route 6"),
        _r(19, "royal-avenue",      "Royal Avenue"),
        _r(20, "route-7",           "Route 7"),
        _r(21, "wela-volcano-park", "Wela Volcano Park",    event="trial2_kiawe",
           note="Trial Captain Kiawe (Fire) — Totem Salazzle (USUM)"),
        _r(22, "route-8",           "Route 8"),
        _r(23, "lush-jungle",       "Lush Jungle",          event="trial3_mallow",
           note="Trial Captain Mallow (Grass) — Totem Lurantis"),
        _r(24, "route-9",           "Route 9"),
        _r(25, "konikoni-city",     "Konikoni City"),
        _r(26, "ruins-of-life",     "Ruins of Life"),
        _r(27, "akala-grand-trial", "Akala Grand Trial",    event="grand_trial2_olivia",
           note="Kahuna Olivia (Rock)"),
        _r(28, "route-10",          "Route 10"),
        _r(29, "route-11",          "Route 11"),
        _r(30, "aether-house",      "Aether House"),
        _r(31, "route-12",          "Route 12"),
        _r(32, "blush-mountain",    "Blush Mountain"),
        _r(33, "route-13",          "Route 13"),
        _r(34, "tapu-village",      "Tapu Village"),
        _r(35, "route-14",          "Route 14"),
        _r(36, "route-15",          "Route 15"),
        _r(37, "ula-ula-meadow",    "Ula'ula Meadow"),
        _r(38, "route-16",          "Route 16"),
        _r(39, "malie-city",        "Malie City"),
        _r(40, "mount-hokulani",    "Mount Hokulani",       event="trial4_sophocles",
           note="Trial Captain Sophocles (Electric) — Totem Togedemaru (USUM)"),
        _r(41, "route-17",          "Route 17"),
        _r(42, "po-town",           "Po Town"),
        _r(43, "mount-lanakila",    "Mount Lanakila (partial)",event="aether_story"),
        _r(44, "aether-paradise",   "Aether Paradise",      event="aether_story2"),
        _r(45, "ultra-space-wilds", "Ultra Space Wilds",    event="ultra_wormhole",
           note="USUM only — Legendary Pokémon via Wormholes"),
        _r(46, "ula-ula-grand-trial","Ula'ula Grand Trial",  event="grand_trial3_nanu",
           note="Kahuna Nanu (Dark)"),
        _r(47, "seafolk-village",   "Seafolk Village"),
        _r(48, "poni-wilds",        "Poni Wilds"),
        _r(49, "ancient-poni-path", "Ancient Poni Path"),
        _r(50, "poni-plains",       "Poni Plains"),
        _r(51, "vast-poni-canyon",  "Vast Poni Canyon",     event="trial5_hapu"),
        _r(52, "poni-grand-trial",  "Poni Grand Trial",     event="grand_trial4_hapu",
           note="Kahuna Hapu (Ground)"),
        _r(53, "altar-of-sunne",    "Altar of the Sunne/Moone",event="story_legendary",
           note="Necrozma storyline; Solgaleo/Lunala encounter"),
        _r(54, "mount-lanakila",    "Mount Lanakila"),
        _r(55, "pokemon-league",    "Pokémon League",
           note="E4: Hala → Olivia → Acerola → Kahili → Professor Kukui / Necroz-Kukui"),
    ],
}

# ── Aliases ────────────────────────────────────────────────────────────────────
ROUTE_ORDER["soulsilver"]     = ROUTE_ORDER["heartgold"]
ROUTE_ORDER["gold"]           = ROUTE_ORDER["heartgold"]
ROUTE_ORDER["silver"]         = ROUTE_ORDER["heartgold"]
ROUTE_ORDER["crystal"]        = ROUTE_ORDER["heartgold"]
ROUTE_ORDER["blue"]           = ROUTE_ORDER["red"]
ROUTE_ORDER["yellow"]         = ROUTE_ORDER["red"]
ROUTE_ORDER["firered"]        = ROUTE_ORDER["red"]
ROUTE_ORDER["leafgreen"]      = ROUTE_ORDER["red"]
ROUTE_ORDER["sapphire"]       = ROUTE_ORDER["ruby"]
ROUTE_ORDER["emerald"]        = ROUTE_ORDER["ruby"]
ROUTE_ORDER["omega-ruby"]     = ROUTE_ORDER["ruby"]
ROUTE_ORDER["alpha-sapphire"] = ROUTE_ORDER["ruby"]
ROUTE_ORDER["pearl"]          = ROUTE_ORDER["diamond"]
ROUTE_ORDER["platinum"]       = ROUTE_ORDER["diamond"]

ROUTE_ORDER["white"]          = ROUTE_ORDER["black"]
ROUTE_ORDER["white-2"]        = ROUTE_ORDER["black-2"]
ROUTE_ORDER["y"]              = ROUTE_ORDER["x"]
ROUTE_ORDER["moon"]           = ROUTE_ORDER["sun"]
ROUTE_ORDER["ultra-moon"]     = ROUTE_ORDER["ultra-sun"]
