"""
Transform raw scraper output → app-ready game.json + species.json + ZIP.

Called at the end of each scrape run — never as a standalone script.
"""

from __future__ import annotations

import json
import re
import zipfile
from collections import defaultdict
from pathlib import Path
from typing import Optional


# ── Display names ──────────────────────────────────────────────────────────────

_DISPLAY_NAMES: dict[str, str] = {
    "red": "Red", "blue": "Blue", "yellow": "Yellow",
    "gold": "Gold", "silver": "Silver", "crystal": "Crystal",
    "ruby": "Ruby", "sapphire": "Sapphire", "emerald": "Emerald",
    "firered": "FireRed", "leafgreen": "LeafGreen",
    "diamond": "Diamond", "pearl": "Pearl", "platinum": "Platinum",
    "heartgold": "HeartGold", "soulsilver": "SoulSilver",
    "black": "Black", "white": "White",
    "black-2": "Black 2", "white-2": "White 2",
    "x": "X", "y": "Y",
    "omega-ruby": "Omega Ruby", "alpha-sapphire": "Alpha Sapphire",
    "sun": "Sun", "moon": "Moon",
    "ultra-sun": "Ultra Sun", "ultra-moon": "Ultra Moon",
}


# ── Swift enum generation ──────────────────────────────────────────────────────

_SWIFT_ENUMS_PATH = Path(__file__).parent.parent / "Nuzlocker/Core/Models/GeneratedEnums.swift"

def _slug_to_swift_id(slug: str) -> str:
    parts = slug.split("-")
    return parts[0] + "".join(p.title() for p in parts[1:])

def _parse_enum_slugs(src: str, enum_name: str) -> set[str]:
    """Extract the set of raw-value slugs already declared in an enum."""
    m = re.search(rf"enum {enum_name}[^{{]*\{{([^}}]*)\}}", src, re.DOTALL)
    if not m:
        return set()
    slugs: set[str] = set()
    for case_m in re.finditer(r'case\s+\w+(?:\s*=\s*"([^"]+)")?', m.group(1)):
        raw = case_m.group(1)
        if raw:
            slugs.add(raw)
        else:
            id_m = re.search(r'case\s+(\w+)', case_m.group(0))
            if id_m:
                slugs.add(id_m.group(1))
    return slugs

def _render_enum_body(slugs: set[str]) -> str:
    lines = []
    for slug in sorted(slugs):
        swift_id = _slug_to_swift_id(slug)
        if swift_id == slug:
            lines.append(f"    case {swift_id}")
        else:
            lines.append(f'    case {swift_id} = "{slug}"')
    return "\n".join(lines)

def _render_swift_enums(methods: set[str], conditions: set[str], triggers: set[str]) -> str:
    return (
        "// Auto-generated by the scraper — do not edit by hand.\n"
        "// Raw values are the PokeAPI slugs used in game data JSON.\n"
        "// New cases are merged in automatically on each scrape run.\n"
        "\n"
        "enum EncounterMethod: String, Codable {\n"
        f"{_render_enum_body(methods)}\n"
        "}\n"
        "\n"
        "enum EncounterCondition: String, Codable {\n"
        f"{_render_enum_body(conditions)}\n"
        "}\n"
        "\n"
        "enum EvolutionTrigger: String, Codable {\n"
        f"{_render_enum_body(triggers)}\n"
        "}\n"
    )

def update_swift_enums(raw: dict) -> None:
    """Merge newly discovered encounter methods/conditions/triggers into the Swift enum file."""
    new_methods: set[str] = set()
    new_conditions: set[str] = set()
    new_triggers: set[str] = set()

    for area in raw["routes"].values():
        for e in area.get("encounters", []):
            new_methods.add(e["method"])
            new_conditions.update(e.get("conditions", []))

    for sp in raw["species"].values():
        for entry in sp.get("evolution_chain", []):
            for evo in entry.get("evolves_via", []):
                new_triggers.add(evo["trigger"])

    existing_src = _SWIFT_ENUMS_PATH.read_text() if _SWIFT_ENUMS_PATH.exists() else ""
    methods    = _parse_enum_slugs(existing_src, "EncounterMethod")    | new_methods
    conditions = _parse_enum_slugs(existing_src, "EncounterCondition") | new_conditions
    triggers   = _parse_enum_slugs(existing_src, "EvolutionTrigger")   | new_triggers

    new_src = _render_swift_enums(methods, conditions, triggers)
    if new_src != existing_src:
        _SWIFT_ENUMS_PATH.write_text(new_src)
        added_m = new_methods    - _parse_enum_slugs(existing_src, "EncounterMethod")
        added_c = new_conditions - _parse_enum_slugs(existing_src, "EncounterCondition")
        added_t = new_triggers   - _parse_enum_slugs(existing_src, "EvolutionTrigger")
        if added_m or added_c or added_t:
            print(f"  Enums   → added {len(added_m)} method(s), {len(added_c)} condition(s), {len(added_t)} trigger(s)")
        else:
            print(f"  Enums   → {_SWIFT_ENUMS_PATH.name} up to date")


# ── Public entry point ─────────────────────────────────────────────────────────

def build_and_write_zip(
    version: str,
    raw: dict,
    sprites_dir: Path,
    maps_dir: Path,
    output_dir: Path,
    trainer_routes: dict | None = None,
) -> Path:
    """Build the variant ZIP and update the global manifest. Returns the ZIP path."""
    game    = _build_game(raw, trainer_routes or {})
    species = _build_species(raw)
    zip_path = _write_zip(version, game, species, sprites_dir, maps_dir, output_dir)
    _update_manifest(raw, output_dir)
    update_swift_enums(raw)
    return zip_path


# ── Global manifest (output/manifest.json) ────────────────────────────────────
#
# One entry per scraped variant. Loaded by the app at launch (or fetched from
# the CDN) to know what games are available. Download URLs are placeholders
# here; scripts/rewrite-manifest.sh patches them for local dev or production.

def _update_manifest(raw: dict, output_dir: Path) -> None:
    manifest_path = output_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {"variants": []}

    version = raw["game"]
    entry = {
        "variantID":      version,
        "gameID":         raw["version_group"].replace("-", "_"),
        "generation":     raw["generation"],
        "displayName":    _DISPLAY_NAMES.get(version, version.replace("-", " ").title()),
        "contentVersion": "1.0.0",
        "layoutVersion":  1,
        "downloadURL":    "",
    }

    # Replace existing entry for this variant or append
    variants = manifest["variants"]
    idx = next((i for i, v in enumerate(variants) if v["variantID"] == version), None)
    if idx is not None:
        variants[idx] = entry
    else:
        variants.append(entry)

    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False))


# ── game.json (VariantContent) ─────────────────────────────────────────────────

def _build_game(raw: dict, trainer_routes: dict) -> dict:
    trainers_by_route = _build_trainer_encounters_by_route(raw["trainers"], trainer_routes)
    first_route = raw["route_order"][0]["location"] if raw["route_order"] else None
    return {
        "variantID":      raw["game"],
        "routes": _build_routes(raw, trainers_by_route, starters=raw["starters"], starter_route=first_route),
        "gyms":   _build_gyms(raw["trainers"]),
        "moves":  _build_moves(raw),
    }


# ── Trainer encounters ─────────────────────────────────────────────────────────

def _slug(name: str) -> str:
    return name.lower().replace(" ", "-").replace(".", "").replace("/", "-").strip("-")


def _group_rival_battles(battles: list[dict]) -> list[list[dict]]:
    """Group rival battles by encounter location.

    Bulbapedia rival pages list battles grouped by location, then by
    player_starter variant within each location. A new group starts when a
    player_starter value recurs (indicating we've moved to the next location).

    Trainers without starter variants (e.g. Hugh, Wally) have no player_starter
    on any battle, so we treat each battle as its own single-entry group.
    """
    if not any(b.get("player_starter") for b in battles):
        return [[b] for b in battles]

    groups: list[list[dict]] = []
    current: list[dict] = []
    seen: set[str] = set()

    for battle in battles:
        ps = battle.get("player_starter")
        if ps is not None and ps in seen:
            if current:
                groups.append(current)
            current = [battle]
            seen = {ps}
        else:
            current.append(battle)
            if ps is not None:
                seen.add(ps)

    if current:
        groups.append(current)

    return groups


def _make_trainer_encounter(trainer: dict, team: list[dict], is_rematch: bool, player_starter: str | None) -> dict:
    return {
        "name":          trainer["name"],
        "specialty":     trainer.get("specialty"),
        "team":          [_transform_member(m) for m in team],
        "isRematch":     is_rematch,
        "playerStarter": player_starter,
    }


def _build_trainer_encounters_by_route(
    trainers: list[dict],
    trainer_routes: dict,
) -> dict[str, list[dict]]:
    """Return {route_id: [TrainerEncounter, ...]} from raw trainer data.

    Rivals are grouped into per-location battle groups and mapped to routes
    using trainer_routes[trainer_name] (a list of route IDs, one per group).
    E4 and champion use trainer_routes[trainer_name] as a single route ID string.
    Trainers not listed in trainer_routes are omitted.
    """
    result: dict[str, list[dict]] = defaultdict(list)

    for trainer in trainers:
        cls  = trainer["class"]
        name = trainer["name"]
        route_def = trainer_routes.get(name)

        if cls == "rival" and isinstance(route_def, list):
            groups = _group_rival_battles(trainer.get("battles", []))
            for group_idx, group in enumerate(groups):
                if group_idx >= len(route_def):
                    break
                route_id = route_def[group_idx]
                if route_id is None:
                    continue
                for battle in group:
                    result[route_id].append(_make_trainer_encounter(
                        trainer,
                        battle["team"],
                        is_rematch=False,
                        player_starter=battle.get("player_starter"),
                    ))

        elif cls in ("elite_four", "champion", "boss") and isinstance(route_def, str):
            if trainer.get("team"):
                result[route_def].append(_make_trainer_encounter(
                    trainer, trainer["team"], is_rematch=False, player_starter=None,
                ))
            if trainer.get("rematch_team"):
                result[route_def].append(_make_trainer_encounter(
                    trainer, trainer["rematch_team"], is_rematch=True, player_starter=None,
                ))

    return dict(result)


# ── Gyms ───────────────────────────────────────────────────────────────────────

def _build_gyms(trainers: list[dict]) -> list[dict]:
    gyms = sorted(
        (t for t in trainers if t["class"] == "gym_leader"),
        key=lambda g: g.get("order", 999),
    )
    return [
        {
            "id":          _slug(g["name"]),
            "leader":      g["name"],
            "badge":       g["badge"],
            "specialty":   g.get("specialty"),
            "region":      g.get("region"),
            "team":        [_transform_member(m) for m in g.get("team", [])],
            "rematchTeam": [_transform_member(m) for m in g["rematch_team"]]
                           if g.get("rematch_team") else None,
        }
        for g in gyms
    ]


def _transform_member(m: dict) -> dict:
    return {
        "id":       m["pokemon_id"],
        "level":    m["level"],
        "moves":    m.get("moves", []),
        "ability":  m.get("ability"),
        "heldItem": m.get("held_item"),
    }


# ── TMs / moves ────────────────────────────────────────────────────────────────

def _build_moves(raw: dict) -> dict:
    # Build machine identifier + location lookup keyed by move slug
    machine_for: dict[str, str] = {}
    location_for: dict[str, str | None] = {}
    for t in raw["tms"]:
        machine_for[t["move"]]  = t["name"]
        location_for[t["move"]] = t.get("location")
    for move_slug, hm_id in raw.get("hm_moves", {}).items():
        machine_for[move_slug]  = hm_id
        location_for[move_slug] = None

    return {
        slug: _transform_move(m, machine_for.get(slug), location_for.get(slug))
        for slug, m in raw["moves"].items()
    }


def _transform_move(m: dict, machine: str | None = None, location: str | None = None) -> dict:
    return {
        "type":         m.get("type", ""),
        "power":        m.get("power"),
        "accuracy":     m.get("accuracy"),
        "pp":           m.get("pp", 0),
        "damageClass":  m.get("damage_class", ""),
        "priority":     m.get("priority", 0),
        "effectChance": m.get("effect_chance"),
        "effect":       m.get("effect", ""),
        "description":  m.get("description", ""),
        "machine":      machine,
        "location":     location,
    }


# ── Routes ─────────────────────────────────────────────────────────────────────

_REGION_PREFIXES = ("johto-", "kanto-", "hoenn-", "sinnoh-", "unova-", "kalos-", "alola-")


def _strip_region(loc: str) -> str:
    for prefix in _REGION_PREFIXES:
        if loc.startswith(prefix):
            loc = loc[len(prefix):]
            break
    # PokeAPI prefixes water routes with "sea-" (e.g. kanto-sea-route-19 → sea-route-19)
    if loc.startswith("sea-route-"):
        loc = loc[4:]
    return loc



def _build_routes(raw: dict, trainers_by_route: dict[str, list[dict]], starters: list[dict], starter_route: str | None) -> list[dict]:
    route_images = raw.get("route_images", {})
    map_files    = raw.get("map_files", {})
    # Index encounter areas by both the full PokeAPI location slug and its
    # region-stripped form so that route_order entries like "route-29" match
    # PokeAPI slugs like "johto-route-29".
    areas_by_loc: dict[str, list[dict]] = defaultdict(list)
    for area in raw["routes"].values():
        full_loc = area["location"]
        areas_by_loc[full_loc].append(area)
        norm_loc = _strip_region(full_loc)
        if norm_loc != full_loc:
            areas_by_loc[norm_loc].append(area)

    statics_by_loc: dict[str, list[dict]] = defaultdict(list)
    for e in raw["static_encounters"]:
        statics_by_loc[e["location"]].append(e)

    gifts_by_loc: dict[str, list[dict]] = defaultdict(list)
    for g in raw["gift_pokemon"]:
        gifts_by_loc[g["location"]].append(g)
    if starter_route:
        for s in starters:
            gifts_by_loc[starter_route].append({
                "pokemon_id": s["pokemon_id"],
                "level":      5,
                "source":     "Professor",
                "note":       s.get("note"),
            })

    trades_by_loc: dict[str, list[dict]] = defaultdict(list)
    for t in raw["in_game_trades"]:
        trades_by_loc[t["location"]].append(t)

    dungeon_floors = raw["dungeon_floors"]
    seen_locs: set[str] = set()
    routes_out: list[dict] = []

    for entry in raw["route_order"]:
        loc_id       = entry["location"]
        display_name = entry["display_name"]
        seen_locs.add(loc_id)
        trainers     = trainers_by_route.get(loc_id, [])

        if loc_id in dungeon_floors:
            floors_out = _build_dungeon_floors(
                dungeon_floors[loc_id], raw["routes"],
                statics_by_loc[loc_id], gifts_by_loc[loc_id], trades_by_loc[loc_id],
                trainers=trainers, map_files=map_files,
            )
        else:
            encs = [e for a in areas_by_loc[loc_id] for e in a.get("encounters", [])]
            floors_out = [_build_floor(
                floor_id=loc_id, display_name=display_name,
                image_file=map_files.get(loc_id), warps=[],
                encounters=encs,
                statics=statics_by_loc[loc_id],
                gifts=gifts_by_loc[loc_id],
                trades=trades_by_loc[loc_id],
                trainers=trainers,
            )]

        routes_out.append({"id": loc_id, "displayName": display_name, "floors": floors_out})

    # Warn about locations with data that didn't make it into route_order.
    # Region-slug catch-alls (e.g. "johto") are intentionally omitted — they're
    # used by PokeAPI for roaming Pokémon with no fixed encounter tile.
    region_catchalls = set(_REGION_PREFIXES) | {"johto", "kanto", "hoenn", "sinnoh", "unova", "kalos", "alola"}
    for loc_id in set(statics_by_loc) | set(gifts_by_loc) | set(trades_by_loc):
        if loc_id not in seen_locs and loc_id not in region_catchalls:
            print(f"  [warn] location '{loc_id}' has static/gift/trade data but is not in route_order")

    return routes_out


def _build_dungeon_floors(
    floors: list[dict],
    all_areas: dict[str, dict],
    statics: list[dict],
    gifts: list[dict],
    trades: list[dict],
    trainers: list[dict],
    map_files: dict[str, str] | None = None,
) -> list[dict]:
    map_files = map_files or {}
    floors_out = []
    for i, floor in enumerate(floors):
        encs = [
            enc
            for area_name in floor.get("pokeapi_areas", [])
            for enc in all_areas.get(area_name, {}).get("encounters", [])
        ]
        floors_out.append(_build_floor(
            floor_id=floor["id"],
            display_name=floor["display_name"],
            image_file=map_files.get(floor["id"]),
            warps=floor.get("warps", []),
            encounters=encs,
            statics=statics if i == 0 else [],
            gifts=gifts   if i == 0 else [],
            trades=trades  if i == 0 else [],
            trainers=trainers if i == 0 else [],
        ))
    return floors_out


def _build_floor(
    floor_id: str,
    display_name: str,
    image_file: Optional[str],
    warps: list[dict],
    encounters: list[dict],
    statics: list[dict],
    gifts: list[dict],
    trades: list[dict],
    trainers: list[dict],
) -> dict:
    return {
        "id":                floor_id,
        "displayName":       display_name,
        "imageFile":         image_file,
        "warps":             [_transform_warp(w) for w in warps],
        "encounters":        [_transform_encounter(e) for e in encounters],
        "staticEncounters":  [_transform_static(e) for e in statics],
        "gifts":             [_transform_gift(g)  for g in gifts],
        "inGameTrades":      [_transform_trade(t) for t in trades],
        "trainerEncounters": trainers,
    }



def _transform_encounter(e: dict) -> dict:
    return {
        "method":     e["method"],
        "id":         e["pokemon_id"],
        "rate":       float(e["chance"]),
        "minLevel":   e["min_level"],
        "maxLevel":   e["max_level"],
        "conditions": e.get("conditions", []),
    }


def _shiny_note(base_note: str | None, always_shiny: bool) -> str | None:
    if always_shiny:
        return f"{base_note} · Always Shiny" if base_note else "Always Shiny"
    return base_note


def _transform_static(e: dict) -> dict:
    return {
        "id":     e["pokemon_id"],
        "level":  e["level"],
        "source": None,
        "note":   _shiny_note(e.get("note"), e.get("always_shiny", False)),
    }


def _transform_gift(g: dict) -> dict:
    return {
        "id":     g["pokemon_id"],
        "level":  g["level"],
        "source": g.get("source"),
        "note":   _shiny_note(g.get("note"), g.get("always_shiny", False)),
    }


def _transform_trade(t: dict) -> dict:
    return {
        "giveID":       t["give_pokemon_id"],
        "receiveID":    t["receive_pokemon_id"],
        "receiveLevel": t.get("receive_level"),
        "npc":          t["npc"],
    }


def _transform_warp(w: dict) -> dict:
    return {
        "x":           w["x"],
        "y":           w["y"],
        "destFloorID": w["dest_floor_id"],
        "destX":       w["dest_x"],
        "destY":       w["dest_y"],
    }


# ── species.json (SpeciesContent) ─────────────────────────────────────────────

def _build_species(raw: dict) -> dict:
    abilities_db = raw.get("abilities", {})

    # Move slug → TM name (e.g. "cut" → "hm01", "earthquake" → "tm26")
    move_to_machine: dict[str, str] = {}
    for t in raw.get("tms", []):
        move_to_machine[t["move"]] = t["name"]
    for move_slug, hm_id in raw.get("hm_moves", {}).items():
        move_to_machine[move_slug] = hm_id

    # Pokemon name → ID (needed to resolve evolution chain targets)
    name_to_id: dict[str, int] = {
        entry["name"]: int(pid)
        for pid, entry in raw["species"].items()
    }

    creatures = [
        _build_creature(entry, abilities_db, move_to_machine, name_to_id)
        for _, entry in sorted(raw["species"].items(), key=lambda x: int(x[0]))
    ]
    return {"creatures": creatures}


def _build_creature(
    entry: dict,
    abilities_db: dict,
    move_to_machine: dict[str, str],
    name_to_id: dict[str, int],
) -> dict:
    stats = entry.get("base_stats", {})

    # evolvesTo: all stage-(N+1) entries in the flat evolution chain.
    # Note: branching lines like Wurmple→Silcoon/Cascoon→Beautifly/Dustox will
    # over-report, but this is an inherent limitation of the flat stage representation.
    evo_chain = entry.get("evolution_chain", [])
    my_name   = entry["name"]
    my_stage  = next((e["stage"] for e in evo_chain if e["pokemon"] == my_name), None)

    evolves_to: list[dict] = []
    if my_stage is not None:
        for evo in evo_chain:
            if evo["stage"] == my_stage + 1 and evo.get("evolves_via"):
                target_id = name_to_id.get(evo["pokemon"])
                if target_id is not None:
                    evolves_to.append({
                        "id":      target_id,
                        "methods": [_transform_evo_method(m) for m in evo["evolves_via"]],
                    })

    # Learnset: level-up moves, then machine moves with resolved TM/HM identifiers
    learnset: list[dict] = []
    for lm in entry.get("moves_by_level", []):
        learnset.append({
            "move":    lm["move"],
            "method":  "level-up",
            "level":   lm["level"],
            "machine": None,
        })
    for mm in entry.get("moves_by_machine", []):
        machine = move_to_machine.get(mm["move"]) or mm.get("machine") or "tm"
        learnset.append({
            "move":    mm["move"],
            "method":  "machine",
            "level":   None,
            "machine": machine,
        })

    # Abilities with descriptions joined from the abilities dict
    abilities: list[dict] = []
    for ab in entry.get("abilities", []):
        ab_info = abilities_db.get(ab["name"], {})
        abilities.append({
            "name":        ab["name"],
            "description": ab_info.get("description") or ab_info.get("short_effect", ""),
            "isHidden":    ab.get("is_hidden", False),
        })

    return {
        "id":         entry["id"],
        "name":       entry["name"],
        "types":      entry.get("types", []),
        "baseStats":  {
            "hp":  stats.get("hp", 0),
            "atk": stats.get("attack", 0),
            "def": stats.get("defense", 0),
            "spe": stats.get("speed", 0),
        },
        "abilities":  abilities,
        "evolvesTo":  evolves_to,
        "learnset":   learnset,
        "spriteFile": f"{entry['id']:03d}.png",
    }


def _transform_evo_method(m: dict) -> dict:
    result: dict = {"trigger": m["trigger"]}
    for src, dst in [
        ("min_level",   "minLevel"),
        ("item",        "item"),
        ("held_item",   "heldItem"),
        ("known_move",  "knownMove"),
        ("time_of_day", "timeOfDay"),
        ("min_happiness", "minHappiness"),
    ]:
        if m.get(src) is not None:
            result[dst] = m[src]
    return result


# ── ZIP ────────────────────────────────────────────────────────────────────────

def _write_zip(version: str, game: dict, species: dict, sprites_dir: Path, maps_dir: Path, output_dir: Path) -> Path:
    out_path = output_dir / f"{version}.zip"
    species_ids = {c["id"] for c in species.get("creatures", [])}

    map_files: set[str] = set()
    for route in game.get("routes", []):
        for floor in route.get("floors", []):
            if f := floor.get("imageFile"):
                map_files.add(f)

    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("game.json",    json.dumps(game,    ensure_ascii=False))
        zf.writestr("species.json", json.dumps(species, ensure_ascii=False))
        for pid in sorted(species_ids):
            sprite = sprites_dir / f"{pid}.png"
            if sprite.exists():
                zf.write(sprite, f"sprites/{pid:03d}.png")
        for filename in sorted(map_files):
            path = maps_dir / filename
            if path.exists():
                zf.write(path, f"maps/{filename}")

    return out_path
