// Generated by scrape/rules.py — do not edit by hand.
// Source: https://nuzlockeuniversity.ca/optional-rules/
import Foundation

enum NuzlockeRule: String, Codable, CaseIterable, Identifiable {
    var id: String { rawValue }

    // MARK: - Harder

    case singlePokemonCenterUse
    case noPokemonCenters
    case levelCaps
    case teamSizeLimit
    case gymLockIn
    case completionistClause
    case setBattleMode
    case noHealingItems
    case oneItemPerBattle
    case foundItemsOnly
    case noBacktracking
    case banSpecificPokemon
    case tierBans
    case noStarter
    case noGiftPokemon
    case noSetupMoves
    case levelUpMovesOnly
    case blindRun
    case noDamageCalculators
    case noHeldItems
    case basePowerLimit
    case noSTABMoves
    case stabOnly
    case noSuperEffectiveMoves
    case singleStagePokemonOnly
    case typeBan
    case monolocke
    case noDualTypes
    case dualTypesOnly
    case typeDiversity
    case noBoxedPokemon
    case sequentialRoster
    case deathlessRun

    // MARK: - Easier

    case reviveAllowance
    case sacrificeRevives
    case giftClause
    case hmSlaveException
    case starterLockIn
    case eggMovesAccess
    case ivNatureModification
    case unlimitedTMs
    case unlimitedMasterBalls
    case escapeReroll
    case higherLevelCap
    case boxSubstitute

    // MARK: - Variety

    case dupesClause
    case shinyClause
    case colorTheme
    case customThematicTeam
    case generationRestriction
    case raidDenEncounters
    case trainerIDStarterRandomizer

    // MARK: - Metadata

    enum Category {
        case harder, easier, variety
    }

    var category: Category {
        switch self {
        case .singlePokemonCenterUse: return .harder
        case .noPokemonCenters: return .harder
        case .levelCaps: return .harder
        case .teamSizeLimit: return .harder
        case .gymLockIn: return .harder
        case .completionistClause: return .harder
        case .setBattleMode: return .harder
        case .noHealingItems: return .harder
        case .oneItemPerBattle: return .harder
        case .foundItemsOnly: return .harder
        case .noBacktracking: return .harder
        case .banSpecificPokemon: return .harder
        case .tierBans: return .harder
        case .noStarter: return .harder
        case .noGiftPokemon: return .harder
        case .noSetupMoves: return .harder
        case .levelUpMovesOnly: return .harder
        case .blindRun: return .harder
        case .noDamageCalculators: return .harder
        case .noHeldItems: return .harder
        case .basePowerLimit: return .harder
        case .noSTABMoves: return .harder
        case .stabOnly: return .harder
        case .noSuperEffectiveMoves: return .harder
        case .singleStagePokemonOnly: return .harder
        case .typeBan: return .harder
        case .monolocke: return .harder
        case .noDualTypes: return .harder
        case .dualTypesOnly: return .harder
        case .typeDiversity: return .harder
        case .noBoxedPokemon: return .harder
        case .sequentialRoster: return .harder
        case .deathlessRun: return .harder
        case .reviveAllowance: return .easier
        case .sacrificeRevives: return .easier
        case .giftClause: return .easier
        case .hmSlaveException: return .easier
        case .starterLockIn: return .easier
        case .eggMovesAccess: return .easier
        case .ivNatureModification: return .easier
        case .unlimitedTMs: return .easier
        case .unlimitedMasterBalls: return .easier
        case .escapeReroll: return .easier
        case .higherLevelCap: return .easier
        case .boxSubstitute: return .easier
        case .dupesClause: return .variety
        case .shinyClause: return .variety
        case .colorTheme: return .variety
        case .customThematicTeam: return .variety
        case .generationRestriction: return .variety
        case .raidDenEncounters: return .variety
        case .trainerIDStarterRandomizer: return .variety
        }
    }

    var displayName: String {
        switch self {
        case .singlePokemonCenterUse: return "Single Pokémon Center Use"
        case .noPokemonCenters: return "No Pokémon Centers"
        case .levelCaps: return "Level Caps"
        case .teamSizeLimit: return "Team Size Limit"
        case .gymLockIn: return "Gym Lock-In"
        case .completionistClause: return "Completionist Clause"
        case .setBattleMode: return "Set Battle Mode"
        case .noHealingItems: return "No Healing Items"
        case .oneItemPerBattle: return "One Item Per Battle"
        case .foundItemsOnly: return "Found Items Only"
        case .noBacktracking: return "No Backtracking"
        case .banSpecificPokemon: return "Ban Specific Pokémon"
        case .tierBans: return "Tier Bans"
        case .noStarter: return "No Starter"
        case .noGiftPokemon: return "No Gift Pokémon"
        case .noSetupMoves: return "No Setup Moves"
        case .levelUpMovesOnly: return "Level-Up Moves Only"
        case .blindRun: return "Blind Run"
        case .noDamageCalculators: return "No Damage Calculators"
        case .noHeldItems: return "No Held Items"
        case .basePowerLimit: return "Base Power Limit"
        case .noSTABMoves: return "No STAB Moves"
        case .stabOnly: return "STAB Only"
        case .noSuperEffectiveMoves: return "No Super-Effective Moves"
        case .singleStagePokemonOnly: return "Single-Stage Pokémon Only"
        case .typeBan: return "Type Ban"
        case .monolocke: return "Monolocke"
        case .noDualTypes: return "No Dual-Types"
        case .dualTypesOnly: return "Dual-Types Only"
        case .typeDiversity: return "Type Diversity"
        case .noBoxedPokemon: return "No Boxed Pokémon"
        case .sequentialRoster: return "Sequential Roster"
        case .deathlessRun: return "Deathless Run"
        case .reviveAllowance: return "Revive Allowance"
        case .sacrificeRevives: return "Sacrifice Revives"
        case .giftClause: return "Gift Clause"
        case .hmSlaveException: return "HM Slave Exception"
        case .starterLockIn: return "Starter Lock-In"
        case .eggMovesAccess: return "Egg Moves Access"
        case .ivNatureModification: return "IV/Nature Modification"
        case .unlimitedTMs: return "Unlimited TMs"
        case .unlimitedMasterBalls: return "Unlimited Master Balls"
        case .escapeReroll: return "Escape Reroll"
        case .higherLevelCap: return "Higher Level Cap"
        case .boxSubstitute: return "Box Substitute"
        case .dupesClause: return "Duplicates Clause"
        case .shinyClause: return "Shiny Clause"
        case .colorTheme: return "Color Theme"
        case .customThematicTeam: return "Custom Thematic Team"
        case .generationRestriction: return "Generation Restriction"
        case .raidDenEncounters: return "Raid Den Encounters"
        case .trainerIDStarterRandomizer: return "Trainer ID Starter Randomizer"
        }
    }

    var description: String {
        switch self {
        case .singlePokemonCenterUse: return "Limit yourself to using each Pokémon Center once."
        case .noPokemonCenters: return "Ban using the Pokémon Center completely!"
        case .levelCaps: return "Enforce Level Caps (your Pokémon can’t be a higher level than the next Gym Leader’s highest-levelled Pokémon – in every Pokémon game)."
        case .teamSizeLimit: return "Limit your team size to the same number of Pokémon as the next Gym Leader."
        case .gymLockIn: return "Once you enter a Gym, you aren’t allowed to leave it until you defeat the Gym Leader."
        case .completionistClause: return "“Completionist Clause”: Force yourself to battle every optional trainer possible before challenging the next Gym."
        case .setBattleMode: return "Use “Set” battle mode."
        case .noHealingItems: return "Ban the use of healing items in battle."
        case .oneItemPerBattle: return "If that seems too tough, limit yourself to one healing item per battle."
        case .foundItemsOnly: return "Alternatively, allow the use of healing items but ONLY the ones you pick up off the ground – no purchasing them."
        case .noBacktracking: return "No turning back – once you leave a route, area, or city, you may not return (unless required to)."
        case .banSpecificPokemon: return "Ban certain powerful Pokémon like Gyarados or Garchomp."
        case .tierBans: return "Ban all Pokémon above a certain “tier” (see our tier list index for some examples)."
        case .noStarter: return "Ban the use of Starter Pokémon (release it after catching your first encounter)."
        case .noGiftPokemon: return "Ban all “Gift” Pokémon (any Pokémon or Egg given to you by an NPC)."
        case .noSetupMoves: return "Ban setup or stat boosting moves like Dragon Dance, Encore, or Substitute."
        case .levelUpMovesOnly: return "Ban TMs – Pokémon are only allowed to use moves they learn by level up."
        case .blindRun: return "Do the run “blind” – ban online references."
        case .noDamageCalculators: return "No damage calculators."
        case .noHeldItems: return "Banning held items."
        case .basePowerLimit: return "Banning moves above a certain Base Power."
        case .noSTABMoves: return "Banning STAB moves."
        case .stabOnly: return "Banning non-STAB moves."
        case .noSuperEffectiveMoves: return "Banning the use of super-effective moves."
        case .singleStagePokemonOnly: return "Use only single-stage and/or not-fully-evolved Pokémon."
        case .typeBan: return "Banning Pokémon of a certain type."
        case .monolocke: return "Use ONLY Pokémon of a certain type (a Monolocke )."
        case .noDualTypes: return "Ban dual-type Pokémon."
        case .dualTypesOnly: return "Use ONLY dual-type Pokémon."
        case .typeDiversity: return "Don’t allow any of your party Pokémon to share a type (only one Water-type, one Fairy-type, and so on- and secondary types count!)."
        case .noBoxedPokemon: return "Any Pokémon that leaves your party (gets placed in the box) can no longer be used."
        case .sequentialRoster: return "You must use encounters in the order they are caught – when a party member faints, the next Pokémon in line replaces them."
        case .deathlessRun: return "Restart if ANY Pokémon faints (a Deathless run)."
        case .reviveAllowance: return "Allow yourself ONE revive (or however many you decide) to bring back a fainted Pokémon."
        case .sacrificeRevives: return "Allow yourself to revive a fainted Pokémon by sacrificing a certain number of your other Pokémon."
        case .giftClause: return "Treat Gift Pokémon as “free” encounters (they don’t count as the encounter for that area). Commonly known as the “Gift Clause”."
        case .hmSlaveException: return "Allow yourself to catch an extra Pokémon for HMs to avoid wasting your real Pokémon’s moveslots."
        case .starterLockIn: return "Pick one Pokémon at the start of the run to “lock in”, you may catch this Pokémon outside of normal encounter rules."
        case .eggMovesAccess: return "Teach your Pokémon egg moves, or other moves that are in their movepool but not normally accessible."
        case .ivNatureModification: return "Modify your Pokémon to be have perfect IVs and/or change their Nature."
        case .unlimitedTMs: return "Give yourself unlimited copies of any TM you acquire."
        case .unlimitedMasterBalls: return "Give yourself unlimited Master Balls to guarantee you catch every encounter."
        case .escapeReroll: return "If the first Pokémon you encounter on a route escapes (Roar, Teleport, etc.) you may choose to not count it and try again."
        case .higherLevelCap: return "If using Level Caps, set your cap a certain number of levels higher than the next Gym Leader."
        case .boxSubstitute: return "Rather than counting a whiteout as a loss, you may continue with a new team of Pokémon from your box."
        case .dupesClause: return "Duplicates Clause (no duplicate encounters, reroll if you encounter a Pokémon you already have – for more details)."
        case .shinyClause: return "Shiny Clause (allow yourself to catch and use any Shiny Pokémon you encounter, even if it would otherwise be against the rules)."
        case .colorTheme: return "Use Pokémon of a certain color."
        case .customThematicTeam: return "Use Pokémon that fit a theme of your choice."
        case .generationRestriction: return "Use only Pokémon that were introduced in the generation you’re playing (ie. playing Platinum and only using Pokémon that were introduced in Gen 4)."
        case .raidDenEncounters: return "Raid Dens: In Pokémon Sword/Shield and Scarlet/Violet, allowing/mandating the use of Raid Dens as an encounter source instead of overworld encounters."
        case .trainerIDStarterRandomizer: return "Randomize your starter choice based on the last digit of your Trainer ID. #1-3 = Grass #4-6 = Water #7-9 = Fire #0 = Player’s choice."
        }
    }
}
